from rest_framework.viewsets import ReadOnlyModelViewSet
from rest_framework.decorators import action
from datetime import timedelta
from django.utils import timezone
import io
from openpyxl import Workbook
from db_inventory.models import Equipment, Component, Consumable, Accessory
from django.db.models import Q, Max

from assignments.models.asset_assignment import ReturnRequest, ReturnRequestItem



def get_latest_snapshot_date(model, *, date_field: str = "date"):
    """
    Returns the most recent snapshot date for a model,
    or None if no data exists.
    """
    return (
        model.objects
        .aggregate(latest=Max(date_field))
        .get("latest")
    )

def get_snapshot_range_start(
    *,
    model,
    days: int,
    date_field: str = "date",
    filters: dict | None = None,
):
    """
    Computes the range start date anchored to the latest
    available snapshot instead of wall-clock time.

    Optionally scopes snapshots using model filters
    (e.g. department=..., location=...).
    """
    qs = model.objects.all()

    if filters:
        qs = qs.filter(**filters)

    latest = qs.order_by(f"-{date_field}").values_list(
        date_field, flat=True
    ).first()

    if not latest:
        return None

    return latest - timedelta(days=days)
    
def build_site_filter(site_type, site_obj, model_class):
    if site_type == "department":
        if model_class == Equipment:
            return Q(room__location__department=site_obj)

        if model_class in [Accessory, Consumable]:
            return Q(room__location__department=site_obj)

        if model_class == Component:
            return Q(equipment__room__location__department=site_obj)

    elif site_type == "location":
        if model_class == Equipment:
            return Q(room__location=site_obj)

        if model_class in [Accessory, Consumable]:
            return Q(room__location=site_obj)

        if model_class == Component:
            return Q(equipment__room__location=site_obj)

    elif site_type == "room":
        if model_class == Equipment:
            return Q(room=site_obj)

        if model_class in [Accessory, Consumable]:
            return Q(room=site_obj)

        if model_class == Component:
            return Q(equipment__room=site_obj)

    raise ValueError(
        f"Unsupported site_type={site_type} or model={model_class.__name__}"
    )


def generate_site_asset_excel(
    site_type,
    site_obj,
    asset_types,
    generated_by=None,
):
    wb = Workbook()
    wb.remove(wb.active)

    asset_model_map = {
        'equipment': {
            'model': Equipment,
            'fields': ['name', 'brand', 'model', 'serial_number', 'public_id']
        },
        'component': {
            'model': Component,
            'fields': ['name', 'brand', 'model', 'serial_number', 'quantity', 'public_id', 'equipment_id']
        },
        'consumable': {
            'model': Consumable,
            'fields': ['name', 'description', 'quantity', 'public_id', 'room_id']
        },
        'accessory': {
            'model': Accessory,
            'fields': ['name', 'serial_number', 'quantity', 'public_id', 'room_id']
        }
    }

    generated_at = timezone.now()
    asset_totals = {}
    asset_querysets = {}

    # 1️⃣ Build querysets & totals FIRST
    for asset_type in asset_types:
        asset_info = asset_model_map.get(asset_type)
        if not asset_info:
            continue

        model = asset_info['model']
        qs = model.objects.filter(
            build_site_filter(site_type, site_obj, model)
        )

        asset_querysets[asset_type] = qs
        asset_totals[asset_type] = qs.count()

    # 2️⃣ Create Report Info sheet
    info_sheet = wb.create_sheet(title="Report Info")

    info_rows = [
        ("Generated At", generated_at.strftime("%Y-%m-%d %H:%M:%S")),
        ("Generated By", generated_by.get_username() if generated_by else "System"),
        ("Site Type", site_type.capitalize()),
        ("Site ID", site_obj.public_id),
        ("", ""),
        ("Asset Totals", ""),
    ]

    for row in info_rows:
        info_sheet.append(row)

    for asset_type, total in asset_totals.items():
        info_sheet.append([asset_type.capitalize(), total])

    # 3️⃣ Create asset sheets
    for asset_type, qs in asset_querysets.items():
        asset_info = asset_model_map[asset_type]
        fields = asset_info['fields']

        sheet = wb.create_sheet(title=asset_type.capitalize())
        sheet.append(fields)

        for obj in qs:
            row = []
            for field in fields:
                if field == 'equipment_id':
                    value = obj.equipment.public_id if obj.equipment else ''
                elif field == 'room_id':
                    value = obj.room.public_id if obj.room else ''
                else:
                    value = getattr(obj, field, '')
                row.append(value)
            sheet.append(row)

    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    return output

def get_return_health():
    now = timezone.now()
    last_24h = now - timedelta(hours=24)
    last_3d = now - timedelta(days=3)
    last_7d = now - timedelta(days=7)

    pending_requests = ReturnRequest.objects.filter(
        status=ReturnRequest.Status.PENDING
    ).count()

    pending_items = ReturnRequestItem.objects.filter(
        status=ReturnRequestItem.Status.PENDING
    ).count()

    stale_requests_24h = ReturnRequest.objects.filter(
        status=ReturnRequest.Status.PENDING,
        requested_at__lt=last_24h
    ).count()

    stale_requests_3d = ReturnRequest.objects.filter(
        status=ReturnRequest.Status.PENDING,
        requested_at__lt=last_3d
    ).count()

    processed_last_24h = ReturnRequest.objects.filter(
        processed_at__gte=last_24h
    ).count()

    created_last_24h = ReturnRequest.objects.filter(
        requested_at__gte=last_24h
    ).count()

    denied_requests_last_7d = ReturnRequest.objects.filter(
        status=ReturnRequest.Status.DENIED,
        processed_at__gte=last_7d
    ).count()

    partial_requests_last_7d = ReturnRequest.objects.filter(
        status=ReturnRequest.Status.PARTIAL,
        processed_at__gte=last_7d
    ).count()

    backlog_ratio = (
        pending_requests / (pending_requests + processed_last_24h)
        if (pending_requests + processed_last_24h) > 0 else 0
    )

    return {
        "backlog": {
            "pending_requests": pending_requests,
            "pending_items": pending_items,
        },
        "aging": {
            "stale_requests_over_24h": stale_requests_24h,
            "stale_requests_over_3d": stale_requests_3d,
        },
        "flow": {
            "created_last_24h": created_last_24h,
            "processed_last_24h": processed_last_24h,
        },
        "quality": {
            "denied_requests_last_7d": denied_requests_last_7d,
            "partial_requests_last_7d": partial_requests_last_7d,
        },
        "insights": {
            "backlog_ratio": round(backlog_ratio, 2),
        }
    }