# Generated by Django 5.2.12 on 2026-04-19 13:25

import django.db.models.deletion
import django.utils.timezone
import users.models.users
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254, unique=True)),
                ('fname', models.CharField(blank=True, default='', max_length=30)),
                ('lname', models.CharField(blank=True, default='', max_length=30)),
                ('job_title', models.CharField(blank=True, default='', max_length=50)),
                ('role', models.CharField(blank=True, default='user', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_system_user', models.BooleanField(default=False)),
                ('force_password_change', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', users.models.users.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('role', models.CharField(choices=[('ROOM_VIEWER', 'Room Viewer'), ('ROOM_CLERK', 'Room Clerk'), ('ROOM_ADMIN', 'Room Admin'), ('LOCATION_VIEWER', 'Location Viewer'), ('LOCATION_ADMIN', 'Location Admin'), ('DEPARTMENT_VIEWER', 'Department Viewer'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('SITE_ADMIN', 'Site Admin')], max_length=40)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='sites.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='sites.location')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='sites.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='users.roleassignment'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['public_id'], name='users_rolea_public__b5ded2_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['role'], name='users_rolea_role_2a99b8_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'role'], name='users_rolea_user_id_f99c5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'SITE_ADMIN'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', True)), models.Q(('role__startswith', 'DEPARTMENT'), ('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('role__startswith', 'LOCATION'), ('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('role__startswith', 'ROOM'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='role_assignment_valid_scope'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'SITE_ADMIN')), fields=('user', 'role'), name='unique_site_admin_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('user', 'role', 'department'), name='unique_department_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('user', 'role', 'location'), name='unique_location_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('user', 'role', 'room'), name='unique_room_role_per_user'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['public_id'], name='users_user_public__73b785_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
    ]
