# Generated by Django 5.2.15 on 2026-06-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('users', '0002_user_failed_login_attempts_user_last_failed_login_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='authorization.role'),
        ),
    ]
