# Generated by Django 5.2.12 on 2026-04-19 13:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('user_public_id', models.CharField(blank=True, max_length=15, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('event_type', models.CharField(help_text='Machine-readable event identifier', max_length=100)),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of the event', max_length=255)),
                ('metadata', models.JSONField(blank=True, help_text='Additional structured event data', null=True)),
                ('target_model', models.CharField(blank=True, help_text='Model name of the affected object', max_length=100, null=True)),
                ('target_id', models.CharField(blank=True, help_text='Public ID of the affected object', max_length=100, null=True)),
                ('target_name', models.CharField(blank=True, help_text='Snapshot of object name at time of event', max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('type', models.CharField(choices=[('report_ready', 'Report Ready'), ('asset_assigned', 'Asset Assigned'), ('password_reset', 'Password Reset'), ('system', 'System')], db_index=True, max_length=100)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicIDRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('model_label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=100)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('schema_version', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_idle_minutes', models.PositiveIntegerField(default=30)),
                ('session_absolute_hours', models.PositiveIntegerField(default=12)),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=5)),
                ('lockout_attempts', models.PositiveIntegerField(default=5)),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=15)),
                ('revoke_sessions_on_password_change', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteNameChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('department', 'Department'), ('location', 'Location'), ('room', 'Room')], db_index=True, max_length=20)),
                ('object_public_id', models.CharField(db_index=True, help_text='Public ID of the renamed site entity', max_length=15)),
                ('old_name', models.CharField(max_length=255)),
                ('new_name', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteRelocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('location', 'Location'), ('room', 'Room')], db_index=True, max_length=20)),
                ('object_public_id', models.CharField(db_index=True, help_text='Public ID of the relocated site entity', max_length=15)),
                ('object_name', models.CharField(help_text='Name of the site at time of relocation', max_length=255, null=True)),
                ('from_parent_public_id', models.CharField(help_text='Previous parent site public ID', max_length=15)),
                ('from_parent_name', models.CharField(help_text='Previous parent site name at time of relocation', max_length=255, null=True)),
                ('to_parent_public_id', models.CharField(help_text='New parent site public ID', max_length=15)),
                ('to_parent_name', models.CharField(help_text='New parent site name at time of relocation', max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(max_length=128, unique=True)),
                ('previous_refresh_token_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('absolute_expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('session_family', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('device_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
