# Generated by Django 5.2.12 on 2026-04-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetevent',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_password_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='publicidregistry',
            index=models.Index(fields=['model_label'], name='core_public_model_l_74c0d1_idx'),
        ),
        migrations.AddField(
            model_name='sitenamechangehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_name_change_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siterelocationhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_relocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type'], name='core_auditl_event_t_04b2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='core_auditl_user_id_2ff9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='core_auditl_target__315580_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_deleted', '-created_at'], name='core_notifi_recipie_aee161_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'level'], name='core_notifi_recipie_fee0da_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='core_notifi_type_2da3a2_idx'),
        ),
        migrations.AddIndex(
            model_name='sitenamechangehistory',
            index=models.Index(fields=['site_type', 'object_public_id'], name='core_sitena_site_ty_72aa01_idx'),
        ),
        migrations.AddIndex(
            model_name='sitenamechangehistory',
            index=models.Index(fields=['changed_at'], name='core_sitena_changed_54ba8c_idx'),
        ),
        migrations.AddIndex(
            model_name='siterelocationhistory',
            index=models.Index(fields=['site_type', 'object_public_id'], name='core_sitere_site_ty_5c902e_idx'),
        ),
        migrations.AddIndex(
            model_name='siterelocationhistory',
            index=models.Index(fields=['changed_at'], name='core_sitere_changed_89404f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='core_userse_user_id_e1c310_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['status'], name='core_userse_status_b6d89b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='core_userse_expires_c40d52_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['absolute_expires_at'], name='core_userse_absolut_7ba0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['refresh_token_hash'], name='core_userse_refresh_ed95c4_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['previous_refresh_token_hash'], name='core_userse_previou_96fa90_idx'),
        ),
    ]
