# Generated by Django 5.2.12 on 2026-05-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysettings',
            name='enable_account_lockout',
            field=models.BooleanField(default=True, help_text='Temporarily lock accounts after repeated failed logins.'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='permanent_lock_threshold',
            field=models.PositiveIntegerField(default=20, help_text='Escalate to admin unlock after repeated abuse.'),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='reset_failed_attempts_after_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Rolling window for failed login attempts.'),
        ),
        migrations.AlterField(
            model_name='securitysettings',
            name='lockout_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Failed attempts before temporary lockout.'),
        ),
        migrations.AlterField(
            model_name='securitysettings',
            name='lockout_duration_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Temporary lockout duration.'),
        ),
    ]
