# Generated by Django 5.2.12 on 2026-05-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_securitysettings_enable_account_lockout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitysettings',
            name='enable_account_lockout',
            field=models.BooleanField(default=False, help_text='Temporarily lock accounts after repeated failed logins.'),
        ),
    ]
