def asset_import_to_workbook_spec(payload: dict) -> dict:
    spec = {}

    meta = payload.get("meta", {})
    data = payload.get("data", {})

    summary = data.get("summary", {})
    issues = data.get("issues", [])

    # -----------------------------
    # Summary Sheet
    # -----------------------------
    spec["Import Summary"] = {
        "headers": ["Field", "Value"],
        "rows": [
            ["Generated At", meta.get("generated_at")],
            ["Generated By", meta.get("generated_by")],
            ["Asset Type", meta.get("asset_type")],
            ["Source File", meta.get("original_file_name")],
            ["Total Rows", summary.get("total_rows", 0)],
            ["Imported Rows", summary.get("imported_rows", 0)],
            ["Skipped Rows", summary.get("skipped_rows", 0)],
            ["Failed Rows", summary.get("failed_rows", 0)],
        ],
    }

    # -----------------------------
    # Issues Sheet
    # -----------------------------
    if issues:
        headers = ["row_number", "status", "reason"]
        rows = [
            [
                issue.get("row_number"),
                issue.get("status"),
                issue.get("reason"),
            ]
            for issue in issues
        ]
    else:
        headers = ["Message"]
        rows = [["No issues detected during import."]]

    spec["Import Issues"] = {
        "headers": headers,
        "rows": rows,
    }

    return spec