# Generated by Django 5.2.12 on 2026-04-16 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='sites.department'),
        ),
        migrations.AddIndex(
            model_name='dailydepartmentsnapshot',
            index=models.Index(fields=['snapshot_date', 'department'], name='analytics_d_snapsho_e7686f_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailydepartmentsnapshot',
            constraint=models.UniqueConstraint(fields=('department', 'snapshot_date'), name='uniq_department_snapshot_per_day'),
        ),
    ]
