# Generated by Django 5.2.12 on 2026-04-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreturnmetrics',
            old_name='requests_created_last_24h',
            new_name='requests_created_today',
        ),
        migrations.RenameField(
            model_name='dailyreturnmetrics',
            old_name='requests_processed_last_24h',
            new_name='requests_processed_today',
        ),
    ]
