# Generated by Django 5.2.12 on 2026-04-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_requests_created_last_24h_dailyreturnmetrics_requests_created_today_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysystemmetrics',
            old_name='active_users_last_24h',
            new_name='active_users_today',
        ),
        migrations.RenameField(
            model_name='dailysystemmetrics',
            old_name='expired_sessions_last_24h',
            new_name='expired_sessions_today',
        ),
        migrations.RenameField(
            model_name='dailysystemmetrics',
            old_name='new_users_last_24h',
            new_name='new_users_today',
        ),
        migrations.RenameField(
            model_name='dailysystemmetrics',
            old_name='unique_users_logged_in_last_24h',
            new_name='unique_users_logged_in_today',
        ),
    ]
