# Generated by Django 5.2.12 on 2026-05-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_rename_active_users_last_24h_dailysystemmetrics_active_users_today_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyauthmetrics',
            old_name='revoked_sessions',
            new_name='revoked_sessions_today',
        ),
        migrations.RenameField(
            model_name='dailyauthmetrics',
            old_name='users_with_revoked_sessions',
            new_name='users_with_revoked_sessions_today',
        ),
        migrations.RenameField(
            model_name='dailysystemmetrics',
            old_name='revoked_sessions',
            new_name='revoked_sessions_today',
        ),
    ]
