# Generated by Django 5.2.15 on 2026-06-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_rename_revoked_sessions_dailyauthmetrics_revoked_sessions_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='total_accessory_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='total_consumable_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='total_equipment_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='total_inventory_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dailysystemmetrics',
            name='total_accessory_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dailysystemmetrics',
            name='total_consumable_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dailysystemmetrics',
            name='total_equipment_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dailysystemmetrics',
            name='total_inventory_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
