
"""
Django settings for inventory project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from datetime import timedelta
import environ 
import os
import sys

IS_TESTING = "test" in sys.argv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------
# Environment detection & configuration
# ------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

IN_DOCKER = os.path.exists("/.dockerenv")

# Default to local unless explicitly told otherwise
DJANGO_ENV = os.environ.get(
    "DJANGO_ENV",
    "dev" if IN_DOCKER else "local",
)

env = environ.Env(DEBUG=(bool, False))

env_file = BASE_DIR / f".env.{DJANGO_ENV}"
if env_file.exists():
    environ.Env.read_env(env_file)
else:
    print(f"Warning: env file not found: {env_file}")

SECRET_KEY = env("SECRET_KEY", default="django-insecure-dev-secret")



DEBUG = env("DEBUG")
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")

if "test" in sys.argv:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": True,
        "handlers": {
            "null": {
                "class": "logging.NullHandler",
            },
        },
        "root": {
            "handlers": ["null"],
            "level": "CRITICAL",
        },
    }
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'db_inventory',

    "core",
    "assets",
    "assignments",
    "sites",
    "users",
    "reporting",
    "analytics",
    "data_import",

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    "django_extensions",

     "django_celery_results",
    "django_celery_beat",
     "channels",
    
]
# -------------------------------------------------
# Redis configuration
# -------------------------------------------------

REDIS_HOST = env("REDIS_HOST", default="redis")
REDIS_PORT = env.int("REDIS_PORT", default=6379)

# Logical Redis DBs (single Redis instance)
REDIS_DB_CELERY = env.int("REDIS_DB_CELERY", default=0)
REDIS_DB_CHANNELS = env.int("REDIS_DB_CHANNELS", default=1)
REDIS_DB_REPORTS = env.int("REDIS_DB_REPORTS", default=2)

REDIS_BASE_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}"

REDIS_CELERY_URL = f"{REDIS_BASE_URL}/{REDIS_DB_CELERY}"
REDIS_CHANNELS_URL = f"{REDIS_BASE_URL}/{REDIS_DB_CHANNELS}"
REDIS_REPORTS_URL = f"{REDIS_BASE_URL}/{REDIS_DB_REPORTS}"

# Report cache
REPORT_CACHE_TTL_SECONDS = env.int("REPORT_CACHE_TTL_SECONDS", default=900)
ASGI_APPLICATION = "inventory.asgi.application"


# -------------------------------------------------
# Report storage (filesystem)
# -------------------------------------------------

REPORTS_DIR = BASE_DIR / "reports"
REPORTS_DIR.mkdir(exist_ok=True)

REPORT_RETENTION_DAYS = env.int("REPORT_RETENTION_DAYS", default=30)

REPORT_DELETE_CRON =  env(
    "TASKRUN_CLEANUP_CRON",
    default="0 12 * * *",
)

REPORT_FILENAME_TEMPLATE = "{report_type}-{public_id}"

# -------------------------------------------------
# Channel layers (WebSockets)
# -------------------------------------------------

if IS_TESTING:
    # Use in-memory layer during tests (no Redis needed)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_CHANNELS_URL],
            },
        },
    }

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "db_inventory.pagination.OptionalPagination",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "db_inventory.authentication.SessionJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": env("THROTTLE_ANON", default="100/hour"),
        "user": env("THROTTLE_USER", default="1000/hour"),

        "login": env("THROTTLE_LOGIN", default="5/min"),
        "token_refresh": env("THROTTLE_REFRESH", default="30/min"),
        "password_reset": env("THROTTLE_PASSWORD_RESET", default="3/hour"),

        "user_read": env("THROTTLE_USER_READ", default="1000/hour"),

        "equipment_action": env("THROTTLE_EQUIPMENT", default="30/hour"),
        "admin_action": env("THROTTLE_ADMIN", default="100/hour"),
    },
}

# Disable throttling during tests
if IS_TESTING:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"] = []

ROOT_URLCONF = 'inventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory.wsgi.application'



DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST", default="db"),
        "PORT": env("DB_PORT", default="5432"),
    }
}
AUTH_USER_MODEL = 'db_inventory.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_TZ = True
TIME_ZONE = env("TIME_ZONE", default="UTC")

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
            'http://localhost:5173', # This is the URL for the React app
            'http://localhost:8000',  # Django development server
        ]


# Allow sending cookies (refresh token)
CORS_ALLOW_CREDENTIALS = True

# Optional: allow specific headers (recommended)
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
    "accept",
    "origin",
    "Content-Disposition",
    "x-device-name",
]

CORS_EXPOSE_HEADERS = [
    "Content-Disposition",
]

SIMPLE_JWT = {
    # Lifetimes
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=env.int("JWT_ACCESS_MINUTES", default=15)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=env.int("JWT_REFRESH_DAYS", default=1)
    ),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "USER_ID_FIELD": "public_id",
    "USER_ID_CLAIM": "public_id",

    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# hide validators during dev to speed up tests
AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    #     'OPTIONS': {
    #         'user_attributes': ('email', 'fname', 'lname'),
    #     }
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 3}
    },
]


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)

EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "no-reply@localhost"

if not DEBUG:
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        raise ValueError(
            "EMAIL_HOST_USER and EMAIL_HOST_PASSWORD must be set in production"
        )

# ----------------------------------------
# Cookie / Security Settings
# ----------------------------------------

# Detect test mode
IS_TESTING = "test" in sys.argv

if DEBUG or IS_TESTING:
    # Local dev + tests (HTTP, Docker-friendly)
    COOKIE_SECURE = False
    COOKIE_SAMESITE = "Lax"

    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False

    # Do NOT force HTTPS redirect in dev
    SECURE_SSL_REDIRECT = False
else:
    # Production (HTTPS only)
    COOKIE_SECURE = True
    COOKIE_SAMESITE = "None"

    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

    SECURE_SSL_REDIRECT = True

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost:5173",
        "http://localhost:8000",
    ],
)

# -------------------------------------------------
# Notification retention (days)
# -------------------------------------------------

## -------------------------------
# Auto-read grace periods
# -------------------------------
NOTIF_INFO_AUTO_READ_DAYS = env.int("NOTIF_INFO_AUTO_READ_DAYS", default=7)
NOTIF_WARNING_AUTO_READ_DAYS = env.int("NOTIF_WARNING_AUTO_READ_DAYS", default=14)
NOTIF_CRITICAL_AUTO_READ_DAYS = env.int("NOTIF_CRITICAL_AUTO_READ_DAYS", default=30)

# -------------------------------
# Soft delete after read
# -------------------------------
NOTIF_INFO_LIFETIME_DAYS = env.int("NOTIF_INFO_LIFETIME_DAYS", default=7)
NOTIF_WARNING_LIFETIME_DAYS  = env.int("NOTIF_WARNING_LIFETIME_DAYS", default=14)
NOTIF_CRITICAL_LIFETIME_DAYS  = env.int("NOTIF_CRITICAL_LIFETIME_DAYS", default=90)

# -------------------------------
# Hard delete after soft delete
# -------------------------------
NOTIF_INFO_PURGE_DAYS = env.int("NOTIF_INFO_PURGE_DAYS", default=3)
NOTIF_WARNING_PURGE_DAYS = env.int("NOTIF_WARNING_PURGE_DAYS", default=7)
NOTIF_CRITICAL_PURGE_DAYS = env.int("NOTIF_CRITICAL_PURGE_DAYS", default=30)

try:
    SESSION_IDLE_MINUTES = int(os.environ["SESSION_IDLE_MINUTES"])
    SESSION_ABSOLUTE_HOURS = int(os.environ["SESSION_ABSOLUTE_HOURS"])
except KeyError as e:
    raise RuntimeError(f"Missing required env var: {e}")

SESSION_IDLE_TIMEOUT = timedelta(minutes=SESSION_IDLE_MINUTES)
SESSION_ABSOLUTE_LIFETIME = timedelta(hours=SESSION_ABSOLUTE_HOURS)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True


CELERY_BROKER_URL = REDIS_CELERY_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


NOTIF_AUTO_READ_CRON = env(
    "NOTIF_AUTO_READ_CRON",
    default="0 2 * * *",  
)

NOTIF_SOFT_DELETE_CRON = env(
    "NOTIF_SOFT_DELETE_CRON",
    default="15 2 * * *", 
)

NOTIF_CLEANUP_CRON = env(
    "NOTIF_CLEANUP_CRON",
    default="30 2 * * *", 
)

TASKRUN_CLEANUP_CRON = env(
    "TASKRUN_CLEANUP_CRON",
    default="0 12 * * *",
)

SNAPSHOT_SCHEMA_VERSION = env.int("SNAPSHOT_SCHEMA_VERSION", default=1)

DAILY_SYSTEM_METRICS_CRON  = env(
    "DAILY_SYSTEM_METRICS_CRON",
    default="0 2 * * *",
)


# ScheduledTaskRun retention
TASKRUN_SUCCESS_RETENTION_DAYS=env.int("TASKRUN_SUCCESS_RETENTION_DAYS", default=7)
TASKRUN_SKIPPED_RETENTION_DAYS=env.int("TASKRUN_SKIPPED_RETENTION_DAYS", default=14)
TASKRUN_FAILED_RETENTION_DAYS=env.int("TASKRUN_FAILED_RETENTION_DAYS", default=90)

USERSESSION_CLEANUP_CRON  = env(
    "USERSESSION_CLEANUP_CRON ",
    default="40 12 * * *",
)
USERSESSION_EXPIRE_CRON=env(
    "USERSESSION_EXPIRE_CRON ",
    default="15 * * * *",
)

SESSION_EXPIRED_RETENTION_DAYS = env.int("SESSION_EXPIRED_RETENTION_DAYS", default=5)
SESSION_REVOKED_RETENTION_DAYS = env.int("SESSION_REVOKED_RETENTION_DAYS", default=20)