# Generated by Django 5.2.12 on 2026-04-15 22:51

import db_inventory.models.users
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0, help_text='Alert when available quantity is at or below this value')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Serial number may contain only letters, numbers, and dashes.', regex='^[A-Z0-9\\-]+$')])),
                ('status', models.CharField(choices=[('ok', 'OK'), ('damaged', 'Damaged'), ('under_repair', 'Under repair'), ('lost', 'Lost'), ('retired', 'Retired'), ('condemned', 'Condemned')], db_index=True, default='ok', max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=100)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('schema_version', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_idle_minutes', models.PositiveIntegerField(default=30)),
                ('session_absolute_hours', models.PositiveIntegerField(default=12)),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=5)),
                ('lockout_attempts', models.PositiveIntegerField(default=5)),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=15)),
                ('revoke_sessions_on_password_change', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254, unique=True)),
                ('fname', models.CharField(blank=True, default='', max_length=30)),
                ('lname', models.CharField(blank=True, default='', max_length=30)),
                ('job_title', models.CharField(blank=True, default='', max_length=50)),
                ('role', models.CharField(blank=True, default='user', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_system_user', models.BooleanField(default=False)),
                ('force_password_change', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', db_inventory.models.users.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='db_inventory.accessory')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_change', models.IntegerField()),
                ('event_type', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('used', 'Used'), ('lost', 'Lost'), ('condemned', 'Condemned'), ('restocked', 'Restocked'), ('adjusted', 'Adjusted'), ('return_requested', 'Return Requested')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db_inventory.accessory')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_accessory_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Remaining quantity currently held by the user')),
                ('issued_quantity', models.PositiveIntegerField(help_text='Original quantity issued in this batch')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When consumables were issued to the user')),
                ('returned_at', models.DateTimeField(blank=True, help_text='Set when all remaining quantity is returned or consumed', null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consumables', to=settings.AUTH_USER_MODEL)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='db_inventory.consumable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_change', models.IntegerField()),
                ('event_type', models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('condemned', 'Condemned'), ('restocked', 'Restocked'), ('adjusted', 'Adjusted'), ('return_requested', 'Return Requested')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db_inventory.consumable')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_consumable_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='db_inventory.consumableissue')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('img_link', models.URLField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['public_id'], name='db_inventor_public__d30f9b_idx'), models.Index(fields=['name'], name='db_inventor_name_9bcc1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('agreement_type', models.CharField(choices=[('warranty', 'Warranty'), ('license', 'License'), ('subscription', 'Subscription'), ('support', 'Support'), ('contract', 'Contract'), ('other', 'Other')], db_index=True, max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('reference_number', models.CharField(blank=True, help_text='Contract number, license key, etc.', max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_notice_days', models.PositiveIntegerField(default=30)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='db_inventory.department')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Serial number may contain only letters, numbers, and dashes.', regex='^[A-Z0-9\\-]+$')])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='db_inventory.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAgreementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.accessory')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db_inventory.assetagreement')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.consumable')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assigned', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_assignment', to='db_inventory.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('repaired', 'Repaired'), ('retired', 'Retired'), ('under_repair', 'Under repair'), ('condemned', 'Condemned'), ('return_requested', 'Return Requested')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db_inventory.equipment')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_equipment_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='db_inventory.department')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='db_inventory.location'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('type', models.CharField(choices=[('report_ready', 'Report Ready'), ('asset_assigned', 'Asset Assigned'), ('password_reset', 'Password Reset'), ('system', 'System')], db_index=True, max_length=100)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_password_resets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicIDRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('model_label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['model_label'], name='db_inventor_model_l_936063_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('partial', 'Partial'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_return_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('role', models.CharField(choices=[('ROOM_VIEWER', 'Room Viewer'), ('ROOM_CLERK', 'Room Clerk'), ('ROOM_ADMIN', 'Room Admin'), ('LOCATION_VIEWER', 'Location Viewer'), ('LOCATION_ADMIN', 'Location Admin'), ('DEPARTMENT_VIEWER', 'Department Viewer'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('SITE_ADMIN', 'Site Admin')], max_length=40)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='db_inventory.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='db_inventory.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='db_inventory.roleassignment'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='db_inventory.location')),
            ],
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='db_inventory.room'),
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('item_type', models.CharField(choices=[('equipment', 'Equipment'), ('accessory', 'Accessory'), ('consumable', 'Consumable')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('accessory_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.accessoryassignment')),
                ('consumable_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.consumableissue')),
                ('equipment_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.equipmentassignment')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db_inventory.returnrequest')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_inventory.room')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='db_inventory.room'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='db_inventory.room'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('user_public_id', models.CharField(blank=True, max_length=15, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('event_type', models.CharField(help_text='Machine-readable event identifier', max_length=100)),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of the event', max_length=255)),
                ('metadata', models.JSONField(blank=True, help_text='Additional structured event data', null=True)),
                ('target_model', models.CharField(blank=True, help_text='Model name of the affected object', max_length=100, null=True)),
                ('target_id', models.CharField(blank=True, help_text='Public ID of the affected object', max_length=100, null=True)),
                ('target_name', models.CharField(blank=True, help_text='Snapshot of object name at time of event', max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='db_inventory.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='db_inventory.location')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='db_inventory.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='db_inventory.room'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='db_inventory.room'),
        ),
        migrations.CreateModel(
            name='SiteNameChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('department', 'Department'), ('location', 'Location'), ('room', 'Room')], db_index=True, max_length=20)),
                ('object_public_id', models.CharField(db_index=True, help_text='Public ID of the renamed site entity', max_length=15)),
                ('old_name', models.CharField(max_length=255)),
                ('new_name', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_name_change_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteRelocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('location', 'Location'), ('room', 'Room')], db_index=True, max_length=20)),
                ('object_public_id', models.CharField(db_index=True, help_text='Public ID of the relocated site entity', max_length=15)),
                ('object_name', models.CharField(help_text='Name of the site at time of relocation', max_length=255, null=True)),
                ('from_parent_public_id', models.CharField(help_text='Previous parent site public ID', max_length=15)),
                ('from_parent_name', models.CharField(help_text='Previous parent site name at time of relocation', max_length=255, null=True)),
                ('to_parent_public_id', models.CharField(help_text='New parent site public ID', max_length=15)),
                ('to_parent_name', models.CharField(help_text='New parent site name at time of relocation', max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_relocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('is_current', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_placements', to='db_inventory.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Room',
                'verbose_name_plural': 'User Rooms',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(max_length=128, unique=True)),
                ('previous_refresh_token_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('absolute_expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('session_family', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('device_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='consumableissue',
            index=models.Index(fields=['consumable', 'user'], name='db_inventor_consuma_7ad576_idx'),
        ),
        migrations.AddIndex(
            model_name='consumableissue',
            index=models.Index(fields=['user', 'returned_at'], name='db_inventor_user_id_a6aa8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('consumable', 'user'), name='unique_open_issue_per_user_consumable'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='consumable_issue_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('issued_quantity__gt', 0)), name='consumable_issue_issued_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__lte', models.F('issued_quantity'))), name='consumable_issue_quantity_lte_issued'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('quantity', 0), _connector='OR'), name='consumable_issue_closed_has_zero_quantity'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['public_id'], name='db_inventor_public__2a52f7_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['name'], name='db_inventor_name_0f686e_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['serial_number'], name='db_inventor_serial__e68698_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['agreement'], name='db_inventor_agreeme_793656_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('consumable__isnull', True), ('equipment__isnull', False)), models.Q(('accessory__isnull', True), ('consumable__isnull', False), ('equipment__isnull', True)), models.Q(('accessory__isnull', False), ('consumable__isnull', True), ('equipment__isnull', True)), _connector='OR'), name='agreement_item_single_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('agreement', 'equipment'), name='unique_equipment_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('consumable__isnull', False)), fields=('agreement', 'consumable'), name='unique_consumable_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('accessory__isnull', False)), fields=('agreement', 'accessory'), name='unique_accessory_per_agreement'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['public_id'], name='db_inventor_public__37e735_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='db_inventor_name_ecd3bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_location_name_per_department'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_deleted', '-created_at'], name='db_inventor_recipie_93ce4a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='db_inventor_recipie_64ca6e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'level'], name='db_inventor_recipie_9564db_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='db_inventor_type_0df374_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='db_inventor_status_23dd91_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['requested_at'], name='db_inventor_request_b41328_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['public_id'], name='db_inventor_public__16bdec_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='db_inventor_email_659b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='db_inventor_role_4ba33e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='db_inventor_is_acti_af5e93_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['public_id'], name='db_inventor_public__f7874c_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='db_inventor_name_a9fbff_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_room_name_per_location'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['public_id'], name='db_inventor_public__ca333c_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['role'], name='db_inventor_role_61a5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'role'], name='db_inventor_user_id_03feac_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'SITE_ADMIN'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', True)), models.Q(('role__startswith', 'DEPARTMENT'), ('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('role__startswith', 'LOCATION'), ('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('role__startswith', 'ROOM'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='role_assignment_valid_scope'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'SITE_ADMIN')), fields=('user', 'role'), name='unique_site_admin_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('user', 'role', 'department'), name='unique_department_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('user', 'role', 'location'), name='unique_location_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('user', 'role', 'room'), name='unique_room_role_per_user'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['item_type'], name='db_inventor_item_ty_d8b21e_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['equipment_assignment'], name='db_inventor_equipme_5c2ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['accessory_assignment'], name='db_inventor_accesso_f50943_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['consumable_issue'], name='db_inventor_consuma_1ae58d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['public_id'], name='db_inventor_public__a3470c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='db_inventor_name_0f9fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='db_inventor_serial__433b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['public_id'], name='db_inventor_public__b5984f_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['name'], name='db_inventor_name_91c998_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type'], name='db_inventor_event_t_f65f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='db_inventor_created_9428ba_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='db_inventor_user_id_84554d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='db_inventor_target__cbea84_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['public_id'], name='db_inventor_public__490e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['agreement_type'], name='db_inventor_agreeme_84e4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['expiry_date'], name='db_inventor_expiry__7d9cea_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='agreement_single_scope'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['public_id'], name='db_inventor_public__ec7dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['name'], name='db_inventor_name_d97ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='sitenamechangehistory',
            index=models.Index(fields=['site_type', 'object_public_id'], name='db_inventor_site_ty_521091_idx'),
        ),
        migrations.AddIndex(
            model_name='sitenamechangehistory',
            index=models.Index(fields=['changed_at'], name='db_inventor_changed_44a2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='siterelocationhistory',
            index=models.Index(fields=['site_type', 'object_public_id'], name='db_inventor_site_ty_297b43_idx'),
        ),
        migrations.AddIndex(
            model_name='siterelocationhistory',
            index=models.Index(fields=['changed_at'], name='db_inventor_changed_9932fd_idx'),
        ),
        migrations.AddIndex(
            model_name='userplacement',
            index=models.Index(fields=['public_id'], name='db_inventor_public__7030aa_idx'),
        ),
        migrations.AddIndex(
            model_name='userplacement',
            index=models.Index(fields=['user'], name='db_inventor_user_id_14638b_idx'),
        ),
        migrations.AddIndex(
            model_name='userplacement',
            index=models.Index(fields=['is_current'], name='db_inventor_is_curr_e0d459_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='unique_current_location_per_user'),
        ),
        migrations.AddConstraint(
            model_name='userplacement',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('room__isnull', False), _connector='OR'), name='current_user_location_requires_room'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='db_inventor_user_id_f8b81f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['status'], name='db_inventor_status_022719_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='db_inventor_expires_7759bb_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['absolute_expires_at'], name='db_inventor_absolut_6bfe29_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['refresh_token_hash'], name='db_inventor_refresh_23a0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['previous_refresh_token_hash'], name='db_inventor_previou_1a7750_idx'),
        ),
    ]
