# Generated by Django 5.2.12 on 2026-04-16 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_inventory', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='sites.room'),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='db_inventory.accessory'),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessoryevent',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db_inventory.accessory'),
        ),
        migrations.AddField(
            model_name='accessoryevent',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_accessory_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessoryevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='sites.department'),
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='sites.location'),
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='sites.room'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.accessory'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db_inventory.assetagreement'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='sites.department'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='sites.location'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='sites.room'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='sites.room'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.consumable'),
        ),
        migrations.AddField(
            model_name='consumableevent',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db_inventory.consumable'),
        ),
        migrations.AddField(
            model_name='consumableevent',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_consumable_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consumables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='db_inventory.consumable'),
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableevent',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='db_inventory.consumableissue'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='sites.room'),
        ),
        migrations.AddField(
            model_name='component',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='db_inventory.equipment'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_assignment', to='db_inventory.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentevent',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db_inventory.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentevent',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_equipment_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetevent',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_password_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='publicidregistry',
            index=models.Index(fields=['model_label'], name='db_inventor_model_l_936063_idx'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='accessory_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.accessoryassignment'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='consumable_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.consumableissue'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='equipment_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.equipmentassignment'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db_inventory.returnrequest'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.room'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='sites.department'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='sites.location'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='sites.room'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='db_inventory.roleassignment'),
        ),
        migrations.AddField(
            model_name='sitenamechangehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_name_change_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siterelocationhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_relocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['public_id'], name='db_inventor_public__ec7dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['name'], name='db_inventor_name_d97ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['public_id'], name='db_inventor_public__490e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['agreement_type'], name='db_inventor_agreeme_84e4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['expiry_date'], name='db_inventor_expiry__7d9cea_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='agreement_single_scope'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type'], name='db_inventor_event_t_f65f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='db_inventor_created_9428ba_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='db_inventor_user_id_84554d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='db_inventor_target__cbea84_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['public_id'], name='db_inventor_public__b5984f_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['name'], name='db_inventor_name_91c998_idx'),
        ),
        migrations.AddIndex(
            model_name='consumableissue',
            index=models.Index(fields=['consumable', 'user'], name='db_inventor_consuma_7ad576_idx'),
        ),
        migrations.AddIndex(
            model_name='consumableissue',
            index=models.Index(fields=['user', 'returned_at'], name='db_inventor_user_id_a6aa8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('consumable', 'user'), name='unique_open_issue_per_user_consumable'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='consumable_issue_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('issued_quantity__gt', 0)), name='consumable_issue_issued_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__lte', models.F('issued_quantity'))), name='consumable_issue_quantity_lte_issued'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('quantity', 0), _connector='OR'), name='consumable_issue_closed_has_zero_quantity'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['public_id'], name='db_inventor_public__a3470c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='db_inventor_name_0f9fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='db_inventor_serial__433b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['public_id'], name='db_inventor_public__2a52f7_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['name'], name='db_inventor_name_0f686e_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['serial_number'], name='db_inventor_serial__e68698_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['agreement'], name='db_inventor_agreeme_793656_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('consumable__isnull', True), ('equipment__isnull', False)), models.Q(('accessory__isnull', True), ('consumable__isnull', False), ('equipment__isnull', True)), models.Q(('accessory__isnull', False), ('consumable__isnull', True), ('equipment__isnull', True)), _connector='OR'), name='agreement_item_single_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('agreement', 'equipment'), name='unique_equipment_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('consumable__isnull', False)), fields=('agreement', 'consumable'), name='unique_consumable_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('accessory__isnull', False)), fields=('agreement', 'accessory'), name='unique_accessory_per_agreement'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_deleted', '-created_at'], name='db_inventor_recipie_93ce4a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='db_inventor_recipie_64ca6e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'level'], name='db_inventor_recipie_9564db_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='db_inventor_type_0df374_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='db_inventor_status_23dd91_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['requested_at'], name='db_inventor_request_b41328_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['item_type'], name='db_inventor_item_ty_d8b21e_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['equipment_assignment'], name='db_inventor_equipme_5c2ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['accessory_assignment'], name='db_inventor_accesso_f50943_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['consumable_issue'], name='db_inventor_consuma_1ae58d_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['public_id'], name='db_inventor_public__ca333c_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['role'], name='db_inventor_role_61a5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'role'], name='db_inventor_user_id_03feac_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'SITE_ADMIN'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', True)), models.Q(('role__startswith', 'DEPARTMENT'), ('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('role__startswith', 'LOCATION'), ('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('role__startswith', 'ROOM'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='role_assignment_valid_scope'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'SITE_ADMIN')), fields=('user', 'role'), name='unique_site_admin_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('user', 'role', 'department'), name='unique_department_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('user', 'role', 'location'), name='unique_location_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('user', 'role', 'room'), name='unique_room_role_per_user'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['public_id'], name='db_inventor_public__16bdec_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='db_inventor_email_659b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='db_inventor_role_4ba33e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='db_inventor_is_acti_af5e93_idx'),
        ),
        migrations.AddIndex(
            model_name='sitenamechangehistory',
            index=models.Index(fields=['site_type', 'object_public_id'], name='db_inventor_site_ty_521091_idx'),
        ),
        migrations.AddIndex(
            model_name='sitenamechangehistory',
            index=models.Index(fields=['changed_at'], name='db_inventor_changed_44a2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='siterelocationhistory',
            index=models.Index(fields=['site_type', 'object_public_id'], name='db_inventor_site_ty_297b43_idx'),
        ),
        migrations.AddIndex(
            model_name='siterelocationhistory',
            index=models.Index(fields=['changed_at'], name='db_inventor_changed_9932fd_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='db_inventor_user_id_f8b81f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['status'], name='db_inventor_status_022719_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='db_inventor_expires_7759bb_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['absolute_expires_at'], name='db_inventor_absolut_6bfe29_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['refresh_token_hash'], name='db_inventor_refresh_23a0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['previous_refresh_token_hash'], name='db_inventor_previou_1a7750_idx'),
        ),
    ]
