# Generated by Django 5.2.12 on 2026-04-18 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_inventory', '0002_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='sites.room'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.consumable'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='sites.room'),
        ),
        migrations.AddField(
            model_name='component',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='db_inventory.equipment'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.equipment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetevent',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_password_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='publicidregistry',
            index=models.Index(fields=['model_label'], name='db_inventor_model_l_936063_idx'),
        ),
        migrations.AddField(
            model_name='sitenamechangehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_name_change_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siterelocationhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_relocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['public_id'], name='db_inventor_public__ec7dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['name'], name='db_inventor_name_d97ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['public_id'], name='db_inventor_public__490e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['agreement_type'], name='db_inventor_agreeme_84e4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['expiry_date'], name='db_inventor_expiry__7d9cea_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='agreement_single_scope'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type'], name='db_inventor_event_t_f65f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='db_inventor_created_9428ba_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='db_inventor_user_id_84554d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='db_inventor_target__cbea84_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['public_id'], name='db_inventor_public__b5984f_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['name'], name='db_inventor_name_91c998_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['public_id'], name='db_inventor_public__a3470c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='db_inventor_name_0f9fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='db_inventor_serial__433b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['public_id'], name='db_inventor_public__2a52f7_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['name'], name='db_inventor_name_0f686e_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['serial_number'], name='db_inventor_serial__e68698_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['agreement'], name='db_inventor_agreeme_793656_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('consumable__isnull', True), ('equipment__isnull', False)), models.Q(('accessory__isnull', True), ('consumable__isnull', False), ('equipment__isnull', True)), models.Q(('accessory__isnull', False), ('consumable__isnull', True), ('equipment__isnull', True)), _connector='OR'), name='agreement_item_single_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('agreement', 'equipment'), name='unique_equipment_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('consumable__isnull', False)), fields=('agreement', 'consumable'), name='unique_consumable_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('accessory__isnull', False)), fields=('agreement', 'accessory'), name='unique_accessory_per_agreement'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_deleted', '-created_at'], name='db_inventor_recipie_93ce4a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='db_inventor_recipie_64ca6e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'level'], name='db_inventor_recipie_9564db_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='db_inventor_type_0df374_idx'),
        ),
        migrations.AddIndex(
            model_name='sitenamechangehistory',
            index=models.Index(fields=['site_type', 'object_public_id'], name='db_inventor_site_ty_521091_idx'),
        ),
        migrations.AddIndex(
            model_name='sitenamechangehistory',
            index=models.Index(fields=['changed_at'], name='db_inventor_changed_44a2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='siterelocationhistory',
            index=models.Index(fields=['site_type', 'object_public_id'], name='db_inventor_site_ty_297b43_idx'),
        ),
        migrations.AddIndex(
            model_name='siterelocationhistory',
            index=models.Index(fields=['changed_at'], name='db_inventor_changed_9932fd_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='db_inventor_user_id_f8b81f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['status'], name='db_inventor_status_022719_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='db_inventor_expires_7759bb_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['absolute_expires_at'], name='db_inventor_absolut_6bfe29_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['refresh_token_hash'], name='db_inventor_refresh_23a0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['previous_refresh_token_hash'], name='db_inventor_previou_1a7750_idx'),
        ),
    ]
