# Generated by Django 5.2.3 on 2025-06-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0003_remove_accessory_location_accessory_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='coutry',
            new_name='country',
        ),
    ]
