# Generated by Django 5.2.3 on 2025-06-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0004_rename_coutry_location_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='component',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
