# Generated by Django 5.2.3 on 2025-06-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0005_component_brand_component_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='identifier',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
