# Generated by Django 5.2.3 on 2025-06-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0007_component_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='identifier',
        ),
    ]
