# Generated by Django 5.2.3 on 2025-07-22 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0009_component_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='address1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='address2',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='department',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='department',
        ),
        migrations.AddField(
            model_name='accessory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db_inventory.department'),
        ),
        migrations.AlterField(
            model_name='component',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.location'),
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_inventory.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
                'unique_together': {('user', 'location')},
            },
        ),
        migrations.DeleteModel(
            name='UserDepartment',
        ),
    ]
