# Generated by Django 5.2.3 on 2025-08-03 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0010_rename_city_location_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='room',
        ),
        migrations.RemoveField(
            model_name='location',
            name='section',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('section', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='db_inventory.location')),
            ],
        ),
    ]
