# Generated by Django 5.2.3 on 2025-08-03 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0011_remove_location_area_remove_location_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.AddField(
            model_name='accessory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.room'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.room'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.room'),
        ),
    ]
