# Generated by Django 5.2.3 on 2025-08-12 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0012_remove_accessory_location_remove_consumable_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlocation',
            options={'verbose_name': 'User Room', 'verbose_name_plural': 'User Rooms'},
        ),
        migrations.AlterUniqueTogether(
            name='userlocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.room'),
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='location',
        ),
    ]
