# Generated by Django 5.2.3 on 2025-08-12 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0013_alter_userlocation_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlocation',
            unique_together={('user', 'room')},
        ),
    ]
