# Generated by Django 5.2.3 on 2025-08-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0014_alter_userlocation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='img_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
