# Generated by Django 5.2.3 on 2025-08-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0016_alter_accessory_name_alter_component_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.RemoveField(
            model_name='component',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='identifier',
        ),
        migrations.AddField(
            model_name='accessory',
            name='public_id',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='component',
            name='public_id',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='consumable',
            name='public_id',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='public_id',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='public_id',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='public_id',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='public_id',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.CharField(editable=False, max_length=15, null=True, unique=True),
        ),
    ]
