# Generated by Django 5.2.3 on 2025-08-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0017_alter_accessory_options_alter_component_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
