# Generated by Django 5.2.3 on 2025-09-03 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0018_alter_accessory_public_id_alter_component_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SITE_ADMIN', 'Site Admin'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('LOCATION_ADMIN', 'Location Admin'), ('ROOM_ADMIN', 'Room Admin'), ('ROOM_CLERK', 'Room Clerk')], max_length=30)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.location')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'department', 'location', 'room')},
            },
        ),
    ]
