# Generated by Django 5.2.3 on 2025-09-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0019_roleassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('SITE_ADMIN', 'Site Admin'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('LOCATION_ADMIN', 'Location Admin'), ('ROOM_ADMIN', 'Room Admin'), ('ROOM_CLERK', 'Room Clerk'), ('VIEWER', 'Viewer')], max_length=30),
        ),
    ]
