# Generated by Django 5.2.3 on 2025-09-04 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0020_alter_roleassignment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='db_inventory.department'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='db_inventory.location'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('ROOM_VIEWER', 'Room Viewer'), ('ROOM_CLERK', 'Room Clerk'), ('ROOM_ADMIN', 'Room Admin'), ('LOCATION_VIEWER', 'Location Viewer'), ('LOCATION_ADMIN', 'Location Admin'), ('DEPARTMENT_VIEWER', 'Department Viewer'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('SITE_ADMIN', 'Site Admin')], max_length=40),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='db_inventory.room'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
