# Generated by Django 5.2.3 on 2025-09-05 11:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0021_alter_roleassignment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
