# Generated by Django 5.2.3 on 2025-09-07 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0022_roleassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='db_inventory.roleassignment'),
        ),
    ]
