# Generated by Django 5.2.3 on 2025-09-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0023_user_active_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='role_public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
