# Generated by Django 5.2.3 on 2025-09-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0026_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='area',
        ),
        migrations.RemoveField(
            model_name='room',
            name='section',
        ),
    ]
