# Generated by Django 5.2.3 on 2025-10-13 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('db_inventory', '0027_remove_room_area_remove_room_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_inventory.room'),
        ),
        migrations.AlterField(
            model_name='component',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_inventory.room'),
        ),
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_inventory.department'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='db_inventory.department'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='db_inventory.location'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='db_inventory.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='db_inventory.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_for_users', to='db_inventory.roleassignment'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_inventory.room'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['public_id'], name='db_inventor_public__2a52f7_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['name'], name='db_inventor_name_0f686e_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['serial_number'], name='db_inventor_serial__e68698_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['equipment'], name='db_inventor_equipme_dfa5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['public_id'], name='db_inventor_public__d30f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='db_inventor_name_9bcc1f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['public_id'], name='db_inventor_public__a3470c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='db_inventor_name_0f9fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='db_inventor_serial__433b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['room'], name='db_inventor_room_id_ac9bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['public_id'], name='db_inventor_public__ca333c_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user'], name='db_inventor_user_id_f7112b_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['role'], name='db_inventor_role_61a5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['department'], name='db_inventor_departm_9d1564_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['location'], name='db_inventor_locatio_1995ee_idx'),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['room'], name='db_inventor_room_id_e277f2_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['public_id'], name='db_inventor_public__f7874c_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='db_inventor_name_a9fbff_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['location'], name='db_inventor_locatio_73fc63_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['public_id'], name='db_inventor_public__16bdec_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='db_inventor_email_659b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='db_inventor_role_4ba33e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='db_inventor_is_acti_af5e93_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='db_inventor_user_id_f8b81f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['status'], name='db_inventor_status_022719_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='db_inventor_expires_7759bb_idx'),
        ),
    ]
