# Generated by Django 5.2.3 on 2025-10-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0028_alter_accessory_room_alter_component_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='component',
            name='db_inventor_equipme_dfa5b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='equipment',
            name='db_inventor_room_id_ac9bd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='roleassignment',
            name='db_inventor_user_id_f7112b_idx',
        ),
        migrations.RemoveIndex(
            model_name='roleassignment',
            name='db_inventor_departm_9d1564_idx',
        ),
        migrations.RemoveIndex(
            model_name='roleassignment',
            name='db_inventor_locatio_1995ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='roleassignment',
            name='db_inventor_room_id_e277f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='db_inventor_locatio_73fc63_idx',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
