# Generated by Django 5.2.3 on 2025-10-19 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0029_remove_component_db_inventor_equipme_dfa5b6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='db_inventory.roleassignment'),
        ),
    ]
