# Generated by Django 5.2.3 on 2025-10-24 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0030_userlocation_is_current_alter_user_active_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_system_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='userlocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='unique_current_location_per_user'),
        ),
    ]
