# Generated by Django 5.2.3 on 2025-11-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0034_user_force_password_change_passwordresetevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresetevent',
            name='db_inventor_user_id_8a9bd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresetevent',
            name='db_inventor_expires_18aba8_idx',
        ),
        migrations.RemoveField(
            model_name='passwordresetevent',
            name='admin',
        ),
        migrations.AddField(
            model_name='passwordresetevent',
            name='reset_token',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
    ]
