# Generated by Django 5.2.3 on 2025-11-23 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0035_remove_passwordresetevent_db_inventor_user_id_8a9bd1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetevent',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_password_resets', to=settings.AUTH_USER_MODEL),
        ),
    ]
