# Generated by Django 5.2.3 on 2025-11-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0036_passwordresetevent_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetevent',
            name='temp_password_hash',
        ),
        migrations.AlterField(
            model_name='passwordresetevent',
            name='reset_token',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
