# Generated by Django 5.2.3 on 2025-11-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0037_remove_passwordresetevent_temp_password_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetevent',
            name='reset_token',
        ),
        migrations.AddField(
            model_name='passwordresetevent',
            name='token',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
