# Generated by Django 5.2.3 on 2025-11-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0038_remove_passwordresetevent_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetevent',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
