# Generated by Django 5.2.3 on 2025-11-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0039_alter_passwordresetevent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetevent',
            name='token',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
