# Generated by Django 5.2.3 on 2025-11-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0040_alter_passwordresetevent_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
