# Generated by Django 5.2.3 on 2025-12-05 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0041_passwordresetevent_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('session_revoked', 'Session Revoked'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('password_reset_request', 'Password Reset Request'), ('password_reset_used', 'Password Reset Used'), ('password_change', 'Password Change'), ('role_assigned', 'Role Assigned'), ('role_revoked', 'Role Revoked'), ('department_created', 'Department Created'), ('location_created', 'Location Created'), ('room_created', 'Room Created'), ('model_updated', 'Model Updated'), ('equipment_created', 'Equipment Created'), ('equipment_updated', 'Equipment Updated'), ('component_updated', 'Component Updated'), ('consumable_updated', 'Consumable Updated'), ('user_moved', 'User Moved')], max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=100, null=True)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type'], name='db_inventor_event_t_f65f4d_idx'), models.Index(fields=['created_at'], name='db_inventor_created_9428ba_idx'), models.Index(fields=['user'], name='db_inventor_user_id_84554d_idx')],
            },
        ),
    ]
