# Generated by Django 5.2.3 on 2025-12-05 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0042_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Extra structured info like changes', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(help_text='Type of event (create, update, delete, login, etc.)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='db_inventor_target__cbea84_idx'),
        ),
    ]
