# Generated by Django 5.2.3 on 2025-12-07 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0043_alter_auditlog_options_auditlog_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_inventory.department'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_inventory.location'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_inventory.room'),
        ),
    ]
