# Generated by Django 5.2.3 on 2025-12-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0045_auditlog_department_name_auditlog_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_public_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
