# Generated by Django 5.2.3 on 2025-12-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0046_auditlog_user_email_auditlog_user_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
