# Generated by Django 5.2.3 on 2025-12-20 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0048_alter_auditlog_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='db_inventory.room'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Human-readable description of the event'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(help_text='Machine-readable event identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional structured event data', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(blank=True, help_text='Public ID of the affected object', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_model',
            field=models.CharField(blank=True, help_text='Model name of the affected object', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_name',
            field=models.CharField(blank=True, help_text='Snapshot of object name at time of event', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='db_inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='db_inventory.room'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='db_inventory.room'),
        ),
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='db_inventory.department'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_locations', to='db_inventory.room'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['public_id'], name='db_inventor_public__ec7dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['name'], name='db_inventor_name_d97ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['public_id'], name='db_inventor_public__b5984f_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['name'], name='db_inventor_name_91c998_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['public_id'], name='db_inventor_public__37e735_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='db_inventor_name_ecd3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['public_id'], name='db_inventor_public__82a769_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user'], name='db_inventor_user_id_1b59e5_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['is_current'], name='db_inventor_is_curr_c91c01_idx'),
        ),
    ]
