# Generated by Django 5.2.3 on 2025-12-20 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0049_alter_accessory_room_alter_auditlog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='db_inventory.room'),
        ),
    ]
