# Generated by Django 5.2.3 on 2025-12-21 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('db_inventory', '0050_alter_consumable_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=15)),
                ('old_name', models.CharField(max_length=255)),
                ('new_name', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reason', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_change_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='db_inventor_content_ad87c6_idx'), models.Index(fields=['changed_at'], name='db_inventor_changed_f79923_idx')],
            },
        ),
    ]
