# Generated by Django 5.2.3 on 2025-12-21 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0051_namechangehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNameChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('department', 'Department'), ('location', 'Location'), ('room', 'Room')], db_index=True, max_length=20)),
                ('object_public_id', models.CharField(db_index=True, help_text='Public ID of the renamed site entity', max_length=15)),
                ('old_name', models.CharField(max_length=255)),
                ('new_name', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_name_change_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.DeleteModel(
            name='NameChangeHistory',
        ),
        migrations.AddIndex(
            model_name='sitenamechangehistory',
            index=models.Index(fields=['site_type', 'object_public_id'], name='db_inventor_site_ty_521091_idx'),
        ),
        migrations.AddIndex(
            model_name='sitenamechangehistory',
            index=models.Index(fields=['changed_at'], name='db_inventor_changed_44a2c4_idx'),
        ),
    ]
