# Generated by Django 5.2.3 on 2025-12-21 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0052_sitenamechangehistory_delete_namechangehistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('location', 'Location'), ('room', 'Room')], db_index=True, max_length=20)),
                ('object_public_id', models.CharField(db_index=True, help_text='Public ID of the relocated site entity', max_length=15)),
                ('from_parent_public_id', models.CharField(help_text='Previous parent site public ID', max_length=15)),
                ('to_parent_public_id', models.CharField(help_text='New parent site public ID', max_length=15)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_relocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['site_type', 'object_public_id'], name='db_inventor_site_ty_26d7eb_idx'), models.Index(fields=['changed_at'], name='db_inventor_changed_c2d57c_idx')],
            },
        ),
    ]
