# Generated by Django 5.2.3 on 2025-12-21 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0053_siterelocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteRelocation',
            new_name='SiteRelocationHistory',
        ),
        migrations.RenameIndex(
            model_name='siterelocationhistory',
            new_name='db_inventor_site_ty_297b43_idx',
            old_name='db_inventor_site_ty_26d7eb_idx',
        ),
        migrations.RenameIndex(
            model_name='siterelocationhistory',
            new_name='db_inventor_changed_9932fd_idx',
            old_name='db_inventor_changed_c2d57c_idx',
        ),
    ]
