# Generated by Django 5.2.3 on 2025-12-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0054_rename_siterelocation_siterelocationhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterelocationhistory',
            name='from_parent_name',
            field=models.CharField(help_text='Previous parent site name at time of relocation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siterelocationhistory',
            name='object_name',
            field=models.CharField(help_text='Name of the site at time of relocation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siterelocationhistory',
            name='to_parent_name',
            field=models.CharField(help_text='New parent site name at time of relocation', max_length=255, null=True),
        ),
    ]
