# Generated by Django 5.2.3 on 2025-12-31 18:37

from django.db import migrations, models


def forwards(apps, schema_editor):
    Equipment = apps.get_model("db_inventory", "Equipment")

    Equipment.objects.filter(
        status__in=["available", "assigned"]
    ).update(status="ok")


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0056_equipment_status_accessoryassignment_accessoryevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(
                choices=[
                    ('ok', 'OK'),
                    ('damaged', 'Damaged'),
                    ('under_repair', 'Under repair'),
                    ('lost', 'Lost'),
                    ('retired', 'Retired'),
                ],
                db_index=True,
                default='ok',
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(forwards),
    ]
