# Generated by Django 5.2.3 on 2026-01-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0057_alter_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentevent',
            name='event_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('repaired', 'Repaired'), ('retired', 'Retired'), ('under_repair', 'Under repair')], max_length=20),
        ),
    ]
