# Generated by Django 5.2.3 on 2026-01-05 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0058_alter_equipmentevent_event_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roleassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Human-readable description of the event', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='component',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Serial number may contain only letters, numbers, and dashes.', regex='^[A-Z0-9\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Serial number may contain only letters, numbers, and dashes.', regex='^[A-Z0-9\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='sitenamechangehistory',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitenamechangehistory',
            name='user_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siterelocationhistory',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='siterelocationhistory',
            name='user_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='roleassignment',
            index=models.Index(fields=['user', 'role'], name='db_inventor_user_id_03feac_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_location_name_per_department'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'SITE_ADMIN'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', True)), models.Q(('role__startswith', 'DEPARTMENT'), ('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('role__startswith', 'LOCATION'), ('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('role__startswith', 'ROOM'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='role_assignment_valid_scope'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'SITE_ADMIN')), fields=('user', 'role'), name='unique_site_admin_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('user', 'role', 'department'), name='unique_department_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('user', 'role', 'location'), name='unique_location_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('user', 'role', 'room'), name='unique_room_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_room_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='userlocation',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('room__isnull', False), _connector='OR'), name='current_user_location_requires_room'),
        ),
    ]
