# Generated by Django 5.2.3 on 2026-01-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0059_alter_roleassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
