# Generated by Django 5.2.3 on 2026-01-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0060_alter_accessory_public_id_alter_auditlog_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
