# Generated by Django 5.2.3 on 2026-01-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0061_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
