# Generated by Django 5.2.3 on 2026-01-06 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0062_alter_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='db_inventory.department'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='db_inventory.location'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='db_inventory.room'),
        ),
    ]
