# Generated by Django 5.2.3 on 2026-01-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0063_alter_roleassignment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='absolute_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['absolute_expires_at'], name='db_inventor_absolut_6bfe29_idx'),
        ),
    ]
