# Generated by Django 5.2.3 on 2026-01-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0064_usersession_absolute_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='absolute_expires_at',
            field=models.DateTimeField(),
        ),
    ]
