# Generated by Django 5.2.3 on 2026-01-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0065_alter_usersession_absolute_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='user_agent_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
