# Generated by Django 5.2.3 on 2026-01-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0066_usersession_user_agent_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='previous_refresh_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
