# Generated by Django 5.2.3 on 2026-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0067_usersession_previous_refresh_token_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoryevent',
            name='quantity',
        ),
        migrations.AddField(
            model_name='accessoryevent',
            name='quantity_change',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessoryevent',
            name='event_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('condemned', 'Condemned'), ('restocked', 'Restocked'), ('adjusted', 'Adjusted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentevent',
            name='event_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('repaired', 'Repaired'), ('retired', 'Retired'), ('under_repair', 'Under repair'), ('condemned', 'Condemned')], max_length=20),
        ),
    ]
