# Generated by Django 5.2.3 on 2026-01-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0068_remove_accessoryevent_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryevent',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
