# Generated by Django 5.2.3 on 2026-01-16 21:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0069_accessoryevent_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumableissue',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='consumableissue',
            name='issued_by',
        ),
        migrations.AddField(
            model_name='consumableevent',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='db_inventory.consumableissue'),
        ),
        migrations.AddField(
            model_name='consumableevent',
            name='quantity_change',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When consumables were issued to the user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consumables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='issued_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Original quantity issued in this batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='returned_at',
            field=models.DateTimeField(blank=True, help_text='Set when all remaining quantity is returned or consumed', null=True),
        ),
        migrations.AlterField(
            model_name='accessoryevent',
            name='event_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('used', 'Used'), ('lost', 'Lost'), ('condemned', 'Condemned'), ('restocked', 'Restocked'), ('adjusted', 'Adjusted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consumableevent',
            name='event_type',
            field=models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('condemned', 'Condemned'), ('restocked', 'Restocked'), ('adjusted', 'Adjusted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consumableissue',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Remaining quantity currently held by the user'),
        ),
        migrations.AlterField(
            model_name='consumableissue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consumableissue',
            index=models.Index(fields=['consumable', 'user'], name='db_inventor_consuma_7ad576_idx'),
        ),
        migrations.AddIndex(
            model_name='consumableissue',
            index=models.Index(fields=['user', 'returned_at'], name='db_inventor_user_id_a6aa8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='consumable_issue_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('issued_quantity__gt', 0)), name='consumable_issue_issued_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__lte', models.F('issued_quantity'))), name='consumable_issue_quantity_lte_issued'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('quantity', 0), _connector='OR'), name='consumable_issue_closed_has_zero_quantity'),
        ),
    ]
