# Generated by Django 5.2.3 on 2026-01-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0070_remove_consumableissue_issued_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('consumable', 'user'), name='unique_open_issue_per_user_consumable'),
        ),
    ]
