# Generated by Django 5.2.3 on 2026-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0071_consumableissue_unique_open_issue_per_user_consumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Alert when available quantity is at or below this value'),
        ),
    ]
