# Generated by Django 5.2.3 on 2026-01-20 22:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0072_consumable_low_stock_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True)),
                ('type', models.CharField(help_text='Machine-readable notification type (e.g. asset_assigned)', max_length=100)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', help_text='Severity level of the notification', max_length=20)),
                ('title', models.CharField(help_text='Short notification title', max_length=150)),
                ('message', models.CharField(help_text='Human-readable message shown to the user', max_length=255)),
                ('entity_type', models.CharField(blank=True, help_text='Model or domain type (e.g. asset)', max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, help_text='Public ID of the related object', max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='db_inventor_recipie_64ca6e_idx'), models.Index(fields=['recipient', 'level'], name='db_inventor_recipie_9564db_idx'), models.Index(fields=['type'], name='db_inventor_type_0df374_idx'), models.Index(fields=['created_at'], name='db_inventor_created_6c8983_idx')],
            },
        ),
    ]
