# Generated by Django 5.2.3 on 2026-01-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0072_consumable_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
