# Generated by Django 5.2.3 on 2026-01-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0073_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
