# Generated by Django 5.2.3 on 2026-01-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0073_alter_user_public_id'),
        ('db_inventory', '0074_notification_deleted_at_notification_is_deleted'),
    ]

    operations = [
    ]
