# Generated by Django 5.2.3 on 2026-01-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0075_merge_20260126_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('damaged', 'Damaged'), ('under_repair', 'Under repair'), ('lost', 'Lost'), ('retired', 'Retired'), ('condemned', 'Condemned')], db_index=True, default='ok', max_length=20, null=True),
        ),
    ]
