# Generated by Django 5.2.3 on 2026-02-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0077_notification_meta_alter_notification_entity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=100)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('schema_version', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
