# Generated by Django 5.2.3 on 2026-02-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0078_scheduledtaskrun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='db_inventor_created_6c8983_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_deleted', '-created_at'], name='db_inventor_recipie_93ce4a_idx'),
        ),
    ]
