# Generated by Django 5.2.3 on 2026-02-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0079_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIDRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('model_label', models.CharField(help_text='app_label.ModelName that reserved this id', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['model_label'], name='db_inventor_model_l_936063_idx')],
            },
        ),
    ]
