# Generated by Django 5.2.3 on 2026-02-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0080_publicidregistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentassignment',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_assignment', to='db_inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentevent',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db_inventory.equipment'),
        ),
    ]
