# Generated by Django 5.2.3 on 2026-02-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0081_alter_equipmentassignment_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
