# Generated by Django 5.2.3 on 2026-02-22 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0082_equipment_deleted_at_equipment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumable',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessoryassignment',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='db_inventory.accessory'),
        ),
        migrations.AlterField(
            model_name='accessoryevent',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db_inventory.accessory'),
        ),
        migrations.AlterField(
            model_name='consumableevent',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='db_inventory.consumable'),
        ),
        migrations.AlterField(
            model_name='consumableissue',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='db_inventory.consumable'),
        ),
    ]
