# Generated by Django 5.2.3 on 2026-03-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0083_accessory_deleted_at_accessory_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_idle_minutes', models.PositiveIntegerField(default=30)),
                ('session_absolute_hours', models.PositiveIntegerField(default=12)),
                ('access_token_minutes', models.PositiveIntegerField(default=5)),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=5)),
                ('lockout_attempts', models.PositiveIntegerField(default=5)),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=15)),
                ('revoke_sessions_on_password_change', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('report_ready', 'Report Ready'), ('asset_assigned', 'Asset Assigned'), ('password_reset', 'Password Reset'), ('system', 'System')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicidregistry',
            name='model_label',
            field=models.CharField(max_length=100),
        ),
    ]
