# Generated by Django 5.2.3 on 2026-03-06 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('db_inventory', '0084_securitysettings_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('agreement_type', models.CharField(choices=[('warranty', 'Warranty'), ('license', 'License'), ('subscription', 'Subscription'), ('support', 'Support'), ('contract', 'Contract'), ('other', 'Other')], db_index=True, max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('reference_number', models.CharField(blank=True, help_text='Contract number, license key, etc.', max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_notice_days', models.PositiveIntegerField(default=30)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetAgreementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_assets', to='db_inventory.assetagreement')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['agreement'], name='db_inventor_agreeme_793656_idx'), models.Index(fields=['content_type', 'object_id'], name='db_inventor_content_f1eac5_idx')],
                'constraints': [models.UniqueConstraint(fields=('agreement', 'content_type', 'object_id'), name='unique_asset_per_agreement')],
            },
        ),
    ]
