# Generated by Django 5.2.3 on 2026-03-07 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0086_assetagreement_department_assetagreement_location_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetagreementitem',
            name='unique_asset_per_agreement',
        ),
        migrations.RemoveIndex(
            model_name='assetagreementitem',
            name='db_inventor_content_f1eac5_idx',
        ),
        migrations.RemoveField(
            model_name='assetagreementitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='assetagreementitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.accessory'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.consumable'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='db_inventory.equipment'),
        ),
        migrations.AlterField(
            model_name='assetagreementitem',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db_inventory.assetagreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('consumable__isnull', True), ('equipment__isnull', False)), models.Q(('accessory__isnull', True), ('consumable__isnull', False), ('equipment__isnull', True)), models.Q(('accessory__isnull', False), ('consumable__isnull', True), ('equipment__isnull', True)), _connector='OR'), name='agreement_item_single_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('agreement', 'equipment'), name='unique_equipment_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('consumable__isnull', False)), fields=('agreement', 'consumable'), name='unique_consumable_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('accessory__isnull', False)), fields=('agreement', 'accessory'), name='unique_accessory_per_agreement'),
        ),
    ]
