# Generated by Django 5.2.3 on 2026-03-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0087_remove_assetagreementitem_unique_asset_per_agreement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitysettings',
            name='access_token_minutes',
        ),
    ]
