# Generated by Django 5.2.3 on 2026-03-15 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0088_remove_securitysettings_access_token_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_return_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True)),
                ('item_type', models.CharField(choices=[('equipment', 'Equipment'), ('accessory', 'Accessory'), ('consumable', 'Consumable')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('accessory_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.accessoryassignment')),
                ('consumable_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.consumableissue')),
                ('equipment_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.equipmentassignment')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db_inventory.returnrequest')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='db_inventor_status_23dd91_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['requested_at'], name='db_inventor_request_b41328_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['item_type'], name='db_inventor_item_ty_d8b21e_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['equipment_assignment'], name='db_inventor_equipme_5c2ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['accessory_assignment'], name='db_inventor_accesso_f50943_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['consumable_issue'], name='db_inventor_consuma_1ae58d_idx'),
        ),
    ]
