# Generated by Django 5.2.3 on 2026-03-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0089_returnrequest_returnrequestitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryevent',
            name='event_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('used', 'Used'), ('lost', 'Lost'), ('condemned', 'Condemned'), ('restocked', 'Restocked'), ('adjusted', 'Adjusted'), ('return_requested', 'Return Requested')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consumableevent',
            name='event_type',
            field=models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('condemned', 'Condemned'), ('restocked', 'Restocked'), ('adjusted', 'Adjusted'), ('return_requested', 'Return Requested')], max_length=20),
        ),
    ]
