# Generated by Django 5.2.3 on 2026-03-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0090_alter_accessoryevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequestitem',
            name='room',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='db_inventory.room'),
            preserve_default=False,
        ),
    ]
