# Generated by Django 5.2.3 on 2026-03-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0091_returnrequestitem_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequestitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentevent',
            name='event_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('repaired', 'Repaired'), ('retired', 'Retired'), ('under_repair', 'Under repair'), ('condemned', 'Condemned'), ('return_requested', 'Return Requested')], max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('partial', 'Partial'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
