# Generated by Django 5.2.3 on 2026-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0092_returnrequestitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequestitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
