# Generated by Django 5.2.3 on 2026-03-21 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0094_alter_returnrequest_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_return_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
