# Generated by Django 5.2.3 on 2026-04-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0095_alter_returnrequest_processed_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLocation',
            new_name='UserPlacement',
        ),
        migrations.RenameIndex(
            model_name='userplacement',
            new_name='db_inventor_public__7030aa_idx',
            old_name='db_inventor_public__82a769_idx',
        ),
        migrations.RenameIndex(
            model_name='userplacement',
            new_name='db_inventor_user_id_14638b_idx',
            old_name='db_inventor_user_id_1b59e5_idx',
        ),
        migrations.RenameIndex(
            model_name='userplacement',
            new_name='db_inventor_is_curr_e0d459_idx',
            old_name='db_inventor_is_curr_c91c01_idx',
        ),
    ]
