# Generated by Django 5.2.3 on 2026-04-03 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0096_rename_userlocation_userplacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplacement',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_placements', to='db_inventory.room'),
        ),
        migrations.AlterField(
            model_name='userplacement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_placements', to=settings.AUTH_USER_MODEL),
        ),
    ]
