# Generated by Django 5.2.3 on 2026-04-04 01:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0097_alter_userplacement_room_alter_userplacement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='device_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_family',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['refresh_token_hash'], name='db_inventor_refresh_23a0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['previous_refresh_token_hash'], name='db_inventor_previou_1a7750_idx'),
        ),
    ]
