# Generated by Django 5.2.3 on 2026-04-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0098_usersession_device_name_usersession_last_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
