# Generated by Django 5.2.12 on 2026-04-19 13:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='sites.room')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('agreement_type', models.CharField(choices=[('warranty', 'Warranty'), ('license', 'License'), ('subscription', 'Subscription'), ('support', 'Support'), ('contract', 'Contract'), ('other', 'Other')], db_index=True, max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('reference_number', models.CharField(blank=True, help_text='Contract number, license key, etc.', max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_notice_days', models.PositiveIntegerField(default=30)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='sites.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='sites.location')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='sites.room')),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0, help_text='Alert when available quantity is at or below this value')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='sites.room')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Serial number may contain only letters, numbers, and dashes.', regex='^[A-Z0-9\\-]+$')])),
                ('status', models.CharField(choices=[('ok', 'OK'), ('damaged', 'Damaged'), ('under_repair', 'Under repair'), ('lost', 'Lost'), ('retired', 'Retired'), ('condemned', 'Condemned')], db_index=True, default='ok', max_length=20, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='sites.room')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Serial number may contain only letters, numbers, and dashes.', regex='^[A-Z0-9\\-]+$')])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='assets.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAgreementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='assets.accessory')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assetagreement')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='assets.consumable')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='assets.equipment')),
            ],
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['public_id'], name='assets_acce_public__72f28b_idx'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['name'], name='assets_acce_name_1aa757_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['public_id'], name='assets_asse_public__b419ef_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['agreement_type'], name='assets_asse_agreeme_fb6bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['expiry_date'], name='assets_asse_expiry__985e8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='agreement_single_scope'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['public_id'], name='assets_cons_public__c940c3_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['name'], name='assets_cons_name_896b86_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['public_id'], name='assets_equi_public__a3a7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='assets_equi_name_aefd46_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='assets_equi_serial__8b6fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['public_id'], name='assets_comp_public__1f88ee_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['name'], name='assets_comp_name_e513cd_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['serial_number'], name='assets_comp_serial__426e14_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['agreement'], name='assets_asse_agreeme_83b696_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('consumable__isnull', True), ('equipment__isnull', False)), models.Q(('accessory__isnull', True), ('consumable__isnull', False), ('equipment__isnull', True)), models.Q(('accessory__isnull', False), ('consumable__isnull', True), ('equipment__isnull', True)), _connector='OR'), name='agreement_item_single_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('agreement', 'equipment'), name='unique_equipment_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('consumable__isnull', False)), fields=('agreement', 'consumable'), name='unique_consumable_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('accessory__isnull', False)), fields=('agreement', 'accessory'), name='unique_accessory_per_agreement'),
        ),
    ]
