# Generated by Django 5.2.12 on 2026-04-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='sites.room'),
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='sites.department'),
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='sites.location'),
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='sites.room'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='assets.accessory'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assetagreement'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='sites.room'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='assets.consumable'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='sites.room'),
        ),
        migrations.AddField(
            model_name='component',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='assets.equipment'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='assets.equipment'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['public_id'], name='assets_acce_public__72f28b_idx'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['name'], name='assets_acce_name_1aa757_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['public_id'], name='assets_asse_public__b419ef_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['agreement_type'], name='assets_asse_agreeme_fb6bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['expiry_date'], name='assets_asse_expiry__985e8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='agreement_single_scope'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['public_id'], name='assets_cons_public__c940c3_idx'),
        ),
        migrations.AddIndex(
            model_name='consumable',
            index=models.Index(fields=['name'], name='assets_cons_name_896b86_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['public_id'], name='assets_equi_public__a3a7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='assets_equi_name_aefd46_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='assets_equi_serial__8b6fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['public_id'], name='assets_comp_public__1f88ee_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['name'], name='assets_comp_name_e513cd_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['serial_number'], name='assets_comp_serial__426e14_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['agreement'], name='assets_asse_agreeme_83b696_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('consumable__isnull', True), ('equipment__isnull', False)), models.Q(('accessory__isnull', True), ('consumable__isnull', False), ('equipment__isnull', True)), models.Q(('accessory__isnull', False), ('consumable__isnull', True), ('equipment__isnull', True)), _connector='OR'), name='agreement_item_single_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('agreement', 'equipment'), name='unique_equipment_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('consumable__isnull', False)), fields=('agreement', 'consumable'), name='unique_consumable_per_agreement'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('accessory__isnull', False)), fields=('agreement', 'accessory'), name='unique_accessory_per_agreement'),
        ),
    ]
