# Generated by Django 5.2.12 on 2026-05-21 04:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('sites', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetagreement',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('pending', 'Pending'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='asset_name_snapshot',
            field=models.CharField(default='MIGRATION_PLACEHOLDER', editable=False, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='asset_public_id_snapshot',
            field=models.CharField(default='', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='asset_serial_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='coverage_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='coverage_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, help_text='Contract number, license key, etc.', max_length=150),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='vendor',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='assetagreementitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['status'], name='assets_asse_status_4d5ada_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['vendor'], name='assets_asse_vendor_d223b5_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['coverage_end'], name='assets_asse_coverag_95f710_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('expiry_date__isnull', True), ('expiry_date__gte', models.F('start_date')), _connector='OR'), name='agreement_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(('renewal_date__isnull', True), ('expiry_date__isnull', True), ('renewal_date__lte', models.F('expiry_date')), _connector='OR'), name='agreement_valid_renewal_date'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_start__isnull', True), ('coverage_end__isnull', True), ('coverage_end__gte', models.F('coverage_start')), _connector='OR'), name='agreement_item_valid_coverage_dates'),
        ),
    ]
