# Generated by Django 5.2.12 on 2026-05-23 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetagreement_currency_assetagreement_renewal_date_and_more'),
        ('sites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('DEPARTMENT', 'Department'), ('LOCATION', 'Location'), ('ROOM', 'Room')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('RENEWED', 'Renewed'), ('EXTENDED', 'Extended'), ('TERMINATED', 'Terminated'), ('STATUS_CHANGED', 'Status Changed')], db_index=True, max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('previous_expiry_date', models.DateField(blank=True, null=True)),
                ('new_expiry_date', models.DateField(blank=True, null=True)),
                ('previous_renewal_date', models.DateField(blank=True, null=True)),
                ('new_renewal_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ATTACHED', 'Attached'), ('REMOVED', 'Removed'), ('INVALIDATED', 'Invalidated'), ('REINSTATED', 'Reinstated'), ('COVERAGE_EXPIRED', 'Coverage Expired')], db_index=True, max_length=30)),
                ('asset_public_id', models.CharField(db_index=True, max_length=50)),
                ('asset_name', models.CharField(max_length=150)),
                ('asset_serial', models.CharField(blank=True, max_length=150)),
                ('asset_type', models.CharField(max_length=30)),
                ('coverage_start', models.DateField(blank=True, null=True)),
                ('coverage_end', models.DateField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('room_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='assetagreement',
            name='agreement_single_scope',
        ),
        migrations.RemoveConstraint(
            model_name='assetagreement',
            name='agreement_valid_dates',
        ),
        migrations.RemoveConstraint(
            model_name='assetagreement',
            name='agreement_valid_renewal_date',
        ),
        migrations.RemoveConstraint(
            model_name='assetagreementitem',
            name='agreement_item_single_asset',
        ),
        migrations.RemoveConstraint(
            model_name='assetagreementitem',
            name='unique_equipment_per_agreement',
        ),
        migrations.RemoveConstraint(
            model_name='assetagreementitem',
            name='unique_consumable_per_agreement',
        ),
        migrations.RemoveConstraint(
            model_name='assetagreementitem',
            name='unique_accessory_per_agreement',
        ),
        migrations.RemoveConstraint(
            model_name='assetagreementitem',
            name='agreement_item_valid_coverage_dates',
        ),
        migrations.RemoveIndex(
            model_name='assetagreement',
            name='assets_asse_expiry__985e8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetagreementitem',
            name='assets_asse_agreeme_83b696_idx',
        ),
        migrations.RemoveField(
            model_name='assetagreement',
            name='department',
        ),
        migrations.RemoveField(
            model_name='assetagreement',
            name='expiry_notice_days',
        ),
        migrations.RemoveField(
            model_name='assetagreement',
            name='location',
        ),
        migrations.RemoveField(
            model_name='assetagreement',
            name='room',
        ),
        migrations.AddField(
            model_name='assetagreement',
            name='managing_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_agreements', to='sites.department'),
        ),
        migrations.AddField(
            model_name='assetagreementitem',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='agreement_type',
            field=models.CharField(choices=[('LICENSE', 'License'), ('WARRANTY', 'Warranty'), ('SERVICE', 'Service'), ('MAINTENANCE', 'Maintenance'), ('SUPPORT', 'Support'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetagreement',
            name='vendor',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetagreementitem',
            name='asset_name_snapshot',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='assetagreementitem',
            name='asset_public_id_snapshot',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='assetagreementitem',
            name='asset_serial_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='assetagreementitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['name'], name='assets_asse_name_6a8617_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['public_id'], name='assets_asse_public__941850_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['coverage_start'], name='assets_asse_coverag_8faaa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('expiry_date__gte', models.F('start_date')), _connector='OR'), name='agreement_expiry_after_start'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(('renewal_date__isnull', True), ('expiry_date__isnull', True), ('renewal_date__lte', models.F('expiry_date')), _connector='OR'), name='agreement_renewal_before_expiry'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equipment__isnull', False), ('consumable__isnull', True), ('accessory__isnull', True)), models.Q(('equipment__isnull', True), ('consumable__isnull', False), ('accessory__isnull', True)), models.Q(('equipment__isnull', True), ('consumable__isnull', True), ('accessory__isnull', False)), _connector='OR'), name='agreement_item_single_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_end__isnull', True), ('coverage_start__isnull', True), ('coverage_end__gte', models.F('coverage_start')), _connector='OR'), name='agreement_item_valid_coverage_dates'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(('equipment__isnull', True), ('quantity', 1), _connector='OR'), name='equipment_agreement_quantity_one'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('agreement', 'equipment'), name='unique_equipment_agreement_item'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('consumable__isnull', False)), fields=('agreement', 'consumable'), name='unique_consumable_agreement_item'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('accessory__isnull', False)), fields=('agreement', 'accessory'), name='unique_accessory_agreement_item'),
        ),
        migrations.AddField(
            model_name='agreementcoverage',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='assets.assetagreement'),
        ),
        migrations.AddField(
            model_name='agreementcoverage',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_coverages', to='sites.department'),
        ),
        migrations.AddField(
            model_name='agreementcoverage',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_coverages', to='sites.location'),
        ),
        migrations.AddField(
            model_name='agreementcoverage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_coverages', to='sites.room'),
        ),
        migrations.AddField(
            model_name='agreementhistory',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.assetagreement'),
        ),
        migrations.AddField(
            model_name='agreementhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementitemhistory',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_history', to='assets.assetagreement'),
        ),
        migrations.AddField(
            model_name='agreementitemhistory',
            name='agreement_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='assets.assetagreementitem'),
        ),
        migrations.AddField(
            model_name='agreementitemhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_item_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agreementcoverage',
            index=models.Index(fields=['public_id'], name='assets_agre_public__1b5b28_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementcoverage',
            index=models.Index(fields=['scope_type'], name='assets_agre_scope_t_e9027d_idx'),
        ),
        migrations.AddConstraint(
            model_name='agreementcoverage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_type', 'GLOBAL'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', True)), models.Q(('scope_type', 'DEPARTMENT'), ('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('scope_type', 'LOCATION'), ('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('scope_type', 'ROOM'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='valid_agreement_coverage_scope'),
        ),
        migrations.AddIndex(
            model_name='agreementitemhistory',
            index=models.Index(fields=['event_type'], name='assets_agre_event_t_6f1fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementitemhistory',
            index=models.Index(fields=['asset_public_id'], name='assets_agre_asset_p_aeb420_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementitemhistory',
            index=models.Index(fields=['created_at'], name='assets_agre_created_0d4eff_idx'),
        ),
    ]
