# Generated by Django 5.2.12 on 2026-05-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_agreementcoverage_agreementhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementhistory',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='agreementhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='agreementitemhistory',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='agreementitemhistory',
            name='agreement_item',
        ),
        migrations.RemoveField(
            model_name='agreementitemhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='assetagreement',
            name='managing_department',
        ),
        migrations.RemoveField(
            model_name='assetagreementitem',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='assetagreementitem',
            name='accessory',
        ),
        migrations.RemoveField(
            model_name='assetagreementitem',
            name='consumable',
        ),
        migrations.RemoveField(
            model_name='assetagreementitem',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='AgreementCoverage',
        ),
        migrations.DeleteModel(
            name='AgreementHistory',
        ),
        migrations.DeleteModel(
            name='AgreementItemHistory',
        ),
        migrations.DeleteModel(
            name='AssetAgreement',
        ),
        migrations.DeleteModel(
            name='AssetAgreementItem',
        ),
    ]
