# Generated by Django 5.2.15 on 2026-06-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_agreementhistory_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per individual unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consumable',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per individual unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
