# Generated by Django 5.2.3 on 2025-12-01 14:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_inventory', '0041_passwordresetevent_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySecurityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('password_resets', models.IntegerField()),
                ('active_password_resets', models.IntegerField()),
                ('expired_password_resets', models.IntegerField()),
                ('users_multiple_active_sessions', models.IntegerField()),
                ('users_with_revoked_sessions', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Security Metric',
                'verbose_name_plural': 'Daily Security Metrics',
            },
        ),
        migrations.CreateModel(
            name='DailySystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField()),
                ('active_users_last_24h', models.IntegerField()),
                ('active_users_last_7d', models.IntegerField()),
                ('new_users_last_24h', models.IntegerField()),
                ('locked_users', models.IntegerField()),
                ('total_sessions', models.IntegerField()),
                ('active_sessions', models.IntegerField()),
                ('revoked_sessions', models.IntegerField()),
                ('expired_sessions_last_24h', models.IntegerField()),
                ('unique_users_logged_in_last_24h', models.IntegerField()),
                ('total_equipment', models.IntegerField()),
                ('total_components', models.IntegerField()),
                ('total_components_quantity', models.IntegerField()),
                ('total_consumables', models.IntegerField()),
                ('total_consumables_quantity', models.IntegerField()),
                ('total_accessories', models.IntegerField()),
                ('total_accessories_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily System Metric',
                'verbose_name_plural': 'Daily System Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRoleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('role', models.CharField(db_index=True, max_length=64)),
                ('total_users_with_role', models.IntegerField()),
                ('total_users_active_with_role', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Role Metric',
                'verbose_name_plural': 'Daily Role Metrics',
                'unique_together': {('date', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DailyDepartmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('total_users', models.IntegerField()),
                ('total_admins', models.IntegerField(default=0)),
                ('total_locations', models.IntegerField()),
                ('total_rooms', models.IntegerField()),
                ('total_equipment', models.IntegerField()),
                ('total_components', models.IntegerField()),
                ('total_component_quantity', models.IntegerField()),
                ('total_consumables', models.IntegerField()),
                ('total_consumables_quantity', models.IntegerField()),
                ('total_accessories', models.IntegerField()),
                ('total_accessories_quantity', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='db_inventory.department')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot_date'], name='inventory_m_snapsho_aef2fd_idx')],
                'unique_together': {('department', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyLocationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('total_users', models.IntegerField()),
                ('total_admins', models.IntegerField(default=0)),
                ('total_rooms', models.IntegerField()),
                ('total_equipment', models.IntegerField()),
                ('total_components', models.IntegerField()),
                ('total_component_quantity', models.IntegerField()),
                ('total_consumables', models.IntegerField()),
                ('total_consumables_quantity', models.IntegerField()),
                ('total_accessories', models.IntegerField()),
                ('total_accessories_quantity', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='db_inventory.location')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot_date'], name='inventory_m_snapsho_d8a59e_idx')],
                'unique_together': {('location', 'snapshot_date')},
            },
        ),
    ]
