# Generated by Django 5.2.3 on 2025-12-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLoginMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_logins', models.IntegerField()),
                ('unique_users_logged_in', models.IntegerField()),
                ('failed_logins', models.IntegerField()),
                ('lockouts', models.IntegerField()),
                ('active_sessions', models.IntegerField()),
                ('revoked_sessions', models.IntegerField()),
                ('expired_sessions', models.IntegerField()),
                ('password_resets_started', models.IntegerField()),
                ('password_resets_completed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Login Metric',
                'verbose_name_plural': 'Daily Login Metrics',
                'ordering': ['-date'],
            },
        ),
    ]
