# Generated by Django 5.2.3 on 2026-01-29 20:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0002_dailyloginmetrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(choices=[('daily', 'Daily')], db_index=True, default='daily', max_length=20)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('data', models.JSONField()),
                ('users_count', models.IntegerField(blank=True, null=True)),
                ('equipment_count', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='celery', max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='inventory_m_created_580f35_idx'), models.Index(fields=['period', 'created_at'], name='inventory_m_period_bdd6a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=32, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('params', models.JSONField()),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='inventory_m_user_id_85cd59_idx'), models.Index(fields=['created_at'], name='inventory_m_created_d6af01_idx')],
            },
        ),
    ]
