# Generated by Django 5.2.3 on 2026-02-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0003_adminmetricssnapshot_reportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysystemmetrics',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
