# Generated by Django 5.2.3 on 2026-02-06 03:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_inventory', '0078_scheduledtaskrun'),
        ('inventory_metrics', '0004_dailysystemmetrics_schema_version'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailydepartmentsnapshot',
            name='inventory_m_snapsho_aef2fd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dailydepartmentsnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='created_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='equipment_damaged',
            field=models.PositiveIntegerField(default=0, help_text='Equipment marked as damaged in this department'),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='equipment_ok',
            field=models.PositiveIntegerField(default=0, help_text='Equipment with status=OK in this department'),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='equipment_under_repair',
            field=models.PositiveIntegerField(default=0, help_text='Equipment currently under repair in this department'),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='total_components_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='snapshot_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='total_accessories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='total_accessories_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='total_admins',
            field=models.PositiveIntegerField(default=0, help_text='Users currently assigned to this department who hold an admin role scoped to this department, its locations/rooms, or globally (SITE_ADMIN).'),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='total_components',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='total_consumables',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='total_consumables_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='total_equipment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='total_locations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailydepartmentsnapshot',
            name='total_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='dailydepartmentsnapshot',
            index=models.Index(fields=['snapshot_date', 'department'], name='inventory_m_snapsho_529321_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailydepartmentsnapshot',
            constraint=models.UniqueConstraint(fields=('department', 'snapshot_date'), name='uniq_department_snapshot_per_day'),
        ),
        migrations.RemoveField(
            model_name='dailydepartmentsnapshot',
            name='total_component_quantity',
        ),
    ]
