# Generated by Django 5.2.3 on 2026-02-07 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0005_remove_dailydepartmentsnapshot_inventory_m_snapsho_aef2fd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylocationsnapshot',
            name='snapshot_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
