# Generated by Django 5.2.3 on 2026-02-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0006_alter_dailylocationsnapshot_snapshot_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAuthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_logins', models.PositiveIntegerField(default=0)),
                ('unique_users_logged_in', models.PositiveIntegerField(default=0)),
                ('failed_logins', models.PositiveIntegerField(default=0)),
                ('lockouts', models.PositiveIntegerField(default=0)),
                ('active_sessions', models.PositiveIntegerField(default=0)),
                ('revoked_sessions', models.PositiveIntegerField(default=0)),
                ('expired_sessions', models.PositiveIntegerField(default=0)),
                ('users_multiple_active_sessions', models.PositiveIntegerField(default=0)),
                ('users_with_revoked_sessions', models.PositiveIntegerField(default=0)),
                ('password_resets_started', models.PositiveIntegerField(default=0)),
                ('password_resets_completed', models.PositiveIntegerField(default=0)),
                ('active_password_resets', models.PositiveIntegerField(default=0)),
                ('expired_password_resets', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Auth Metric',
                'verbose_name_plural': 'Daily Auth Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='AdminMetricsSnapshot',
        ),
        migrations.AlterUniqueTogether(
            name='dailylocationsnapshot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailylocationsnapshot',
            name='location',
        ),
        migrations.DeleteModel(
            name='DailyLoginMetrics',
        ),
        migrations.DeleteModel(
            name='DailyRoleMetrics',
        ),
        migrations.DeleteModel(
            name='DailySecurityMetrics',
        ),
        migrations.AddField(
            model_name='dailysystemmetrics',
            name='equipment_damaged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysystemmetrics',
            name='equipment_ok',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysystemmetrics',
            name='equipment_under_repair',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='active_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='active_users_last_24h',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='active_users_last_7d',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='expired_sessions_last_24h',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='locked_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='new_users_last_24h',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='revoked_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='total_accessories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='total_accessories_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='total_components',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='total_components_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='total_consumables',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='total_consumables_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='total_equipment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='total_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='total_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysystemmetrics',
            name='unique_users_logged_in_last_24h',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DailyLocationSnapshot',
        ),
    ]
