# Generated by Django 5.2.3 on 2026-02-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0007_dailyauthmetrics_delete_adminmetricssnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyauthmetrics',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
