# Generated by Django 5.2.3 on 2026-02-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0008_dailyauthmetrics_schema_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysystemmetrics',
            name='human_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysystemmetrics',
            name='system_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
