# Generated by Django 5.2.3 on 2026-03-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0009_dailysystemmetrics_human_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReturnMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('pending_requests', models.PositiveIntegerField(default=0)),
                ('approved_requests', models.PositiveIntegerField(default=0)),
                ('denied_requests', models.PositiveIntegerField(default=0)),
                ('partial_requests', models.PositiveIntegerField(default=0)),
                ('completed_requests', models.PositiveIntegerField(default=0)),
                ('requests_created_last_24h', models.PositiveIntegerField(default=0)),
                ('requests_processed_last_24h', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('pending_items', models.PositiveIntegerField(default=0)),
                ('approved_items', models.PositiveIntegerField(default=0)),
                ('denied_items', models.PositiveIntegerField(default=0)),
                ('equipment_items', models.PositiveIntegerField(default=0)),
                ('accessory_items', models.PositiveIntegerField(default=0)),
                ('consumable_items', models.PositiveIntegerField(default=0)),
                ('avg_processing_time_ms', models.PositiveIntegerField(default=0)),
                ('max_processing_time_ms', models.PositiveIntegerField(default=0)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
