# Generated by Django 5.2.3 on 2026-03-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0010_dailyreturnmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='approved_return_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='denied_return_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='partial_return_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='pending_return_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='returns_created_last_24h',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='returns_processed_last_24h',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydepartmentsnapshot',
            name='total_return_requests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
