# Generated by Django 5.2.3 on 2026-03-22 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0011_dailydepartmentsnapshot_approved_return_requests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreturnmetrics',
            old_name='avg_processing_time_ms',
            new_name='avg_processing_time_seconds',
        ),
        migrations.RemoveField(
            model_name='dailyreturnmetrics',
            name='max_processing_time_ms',
        ),
    ]
