# Generated by Django 5.2.3 on 2026-03-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0012_rename_avg_processing_time_ms_dailyreturnmetrics_avg_processing_time_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreturnmetrics',
            name='max_processing_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
