# Generated by Django 5.2.12 on 2026-04-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0013_dailyreturnmetrics_max_processing_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportjob',
            name='error_report_csv',
            field=models.TextField(blank=True),
        ),
    ]
