# Generated by Django 5.2.12 on 2026-04-06 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0014_reportjob_error_report_csv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('user_summary', 'User Summary'), ('site_assets', 'Site Assets'), ('site_audit_logs', 'Site Audit Logs'), ('asset_import', 'Asset Import')], db_index=True, default=3, max_length=40),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['user', 'report_type'], name='inventory_m_user_id_aba359_idx'),
        ),
    ]
