# Generated by Django 5.2.12 on 2026-04-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0015_reportjob_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportjob',
            name='report_file',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
