# Generated by Django 5.2.12 on 2026-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_metrics', '0016_reportjob_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportjob',
            name='error_report_csv',
        ),
        migrations.AddField(
            model_name='reportjob',
            name='result_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
