def asset_history_to_workbook_spec(payload: dict) -> dict:

    if not payload:
        raise ValueError("Empty asset history payload")

    spec = {}

    meta = payload.get("meta", {})
    data = payload.get("data", {})

    asset_info = data.get("asset_information", {})
    timeline = data.get("timeline", [])
    summary = data.get("summary", {})

    # -------------------------------------------------
    # Report Information Sheet
    # -------------------------------------------------

    report_rows = [
        ["Report Type", "Asset History"],
        ["Generated At", meta.get("generated_at")],
        ["Generated By", meta.get("generated_by")],
        ["Generated By ID", meta.get("generated_by_id")],
        ["Asset Identifier", data.get("asset_identifier")],
        ["Asset Type", data.get("asset_type")],
        ["Start Date", data.get("start_date")],
        ["End Date", data.get("end_date")],
        ["Timeline Filter Applied", "Yes" if data.get("timeline_filter_applied") else "No"]
    ]

    spec["Report Information"] = {
        "headers": ["Field", "Value"],
        "rows": report_rows,
    }

    # -------------------------------------------------
    # Asset Information Sheet
    # -------------------------------------------------

    if asset_info:
        asset_rows = [
            [key.replace("_", " ").title(), value]
            for key, value in asset_info.items()
        ]
    else:
        asset_rows = [["Message", "No asset information available"]]

    spec["Asset Information"] = {
        "headers": ["Field", "Value"],
        "rows": asset_rows,
    }

    # -------------------------------------------------
    # Event Timeline Sheet
    # -------------------------------------------------

    if timeline:

        timeline_rows = []

        for event in timeline:

            timeline_rows.append([
                event.get("occurred_at"),
                event.get("event_type"),
                event.get("user"),
                event.get("quantity"),
                event.get("quantity_change"),
                event.get("notes"),
                event.get("reported_by"),
            ])

    else:

        timeline_rows = [["No events found for this asset", "", "", "", "", "", ""]]

    spec["Event Timeline"] = {
        "headers": [
            "Occurred At",
            "Event Type",
            "User",
            "Quantity",
            "Quantity Change",
            "Notes",
            "Reported By",
        ],
        "rows": timeline_rows,
    }

    # -------------------------------------------------
    # Event Summary Sheet
    # -------------------------------------------------

    if summary:

        summary_rows = [
            [event_type, count]
            for event_type, count in summary.items()
        ]

    else:

        summary_rows = [["No summary data available", ""]]

    spec["Event Summary"] = {
        "headers": ["Event Type", "Count"],
        "rows": summary_rows,
    }

    return spec