def asset_history_to_workbook_spec(payload: dict) -> dict:

    if not payload:
        raise ValueError("Empty asset history payload")

    spec = {}

    meta = payload["meta"]
    data = payload["data"]

    asset_info = data["asset_information"]
    timeline = data["timeline"]
    summary = data["summary"]

    # ---------------------------------
    # Report Information
    # ---------------------------------

    spec["Report Information"] = {
        "headers": ["Field", "Value"],
        "rows": [
            ["Report Type", meta["report_name"]],
            ["Generated At", meta["generated_at"]],
            ["Generated By", meta["generated_by"]],
            ["Asset Identifier", data["asset_identifier"]],
            ["Asset Type", data["asset_type"]],
            ["Start Date", data["start_date"]],
            ["End Date", data["end_date"]],
            [
                "Timeline Filter Applied",
                "Yes" if data["timeline_filter_applied"] else "No"
            ],
        ],
    }

    # ---------------------------------
    # Asset Information
    # ---------------------------------

    spec["Asset Information"] = {
        "headers": ["Field", "Value"],
        "rows": [
            [k.replace("_", " ").title(), v]
            for k, v in asset_info.items()
        ],
    }

    # ---------------------------------
    # Event Timeline
    # ---------------------------------

    if timeline:
        headers = list(timeline[0].keys())
        rows = [[row.get(h) for h in headers] for row in timeline]
    else:
        headers = ["Message"]
        rows = [["No events found for this asset"]]

    spec["Event Timeline"] = {
        "headers": headers,
        "rows": rows,
    }

    # ---------------------------------
    # Event Summary
    # ---------------------------------

    if summary:
        rows = [[k, v] for k, v in summary.items()]
    else:
        rows = [["No summary data available", ""]]

    spec["Event Summary"] = {
        "headers": ["Event Type", "Count"],
        "rows": rows,
    }

    return spec