def inventory_summary_to_workbook_spec(payload: dict) -> dict:
    """
    Convert canonical inventory summary payload
    into workbook spec with clearer business labels.
    """

    if not payload:
        raise ValueError("Empty inventory summary payload")

    meta = payload.get("meta", {})
    data = payload.get("data", {})

    spec = {}

    # =====================================================
    # Overview Sheet
    # =====================================================
    overview = data.get("overview", {})
    scope_summary = data.get("scope_summary", {})

    rows = [
        ["Report Name", meta.get("report_name")],
        ["Generated At", meta.get("generated_at")],
        ["Generated By", meta.get("generated_by")],
        ["Scope Level", scope_summary.get("scope")],
        ["Scope Name", scope_summary.get("scope_name")],
        ["Departments Included", scope_summary.get("departments")],
        ["Locations Included", scope_summary.get("locations")],
        ["Rooms Included", scope_summary.get("rooms")],
        ["Users In Scope (Current Placement)", scope_summary.get("users")],
        [],
        ["Total Equipment Records", overview.get("total_equipment", 0)],
        ["Total Accessory Units", overview.get("total_accessories_units", 0)],
        ["Total Consumable Units In Stock", overview.get("total_consumables_units", 0)],
        ["Total Users In Scope", overview.get("total_users", 0)],
        [
            "Equipment Utilization % (Assigned ÷ Usable)",
            overview.get("equipment_utilization_percent", 0),
        ],
        [
            "Floating Equipment (Usable & Unassigned)",
            overview.get("floating_equipment", 0),
        ],
        [
            "Low Stock Consumables (At / Below Threshold)",
            overview.get("low_stock_consumables", 0),
        ],
        ["Damaged Equipment", overview.get("damaged_assets", 0)],
        ["Lost Equipment", overview.get("lost_assets", 0)],
    ]

    spec["Overview"] = {
        "headers": ["Metric", "Value"],
        "rows": rows,
    }

    # =====================================================
    # Equipment Sheet
    # =====================================================
    equipment = data.get("equipment", {})

    rows = [
        ["Total Equipment Records", equipment.get("total", 0)],
        [
            "Usable Equipment (Excludes Retired / Condemned)",
            equipment.get("usable", 0),
        ],
        ["Currently Assigned Equipment", equipment.get("assigned", 0)],
        ["Currently Unassigned Equipment", equipment.get("unassigned", 0)],
        ["Operational / OK", equipment.get("ok", 0)],
        ["Damaged", equipment.get("damaged", 0)],
        ["Under Repair", equipment.get("under_repair", 0)],
        ["Equipment Currently Marked Lost", equipment.get("lost", 0)],
        ["Equipment Marked Retired", equipment.get("retired", 0)],
        ["Equipment Marked Condemned", equipment.get("condemned", 0)],
        [
            "Utilization % (Assigned ÷ Usable)",
            equipment.get("utilization_percent", 0),
        ],
    ]

    spec["Equipment"] = {
        "headers": ["Metric", "Value"],
        "rows": rows,
    }

    # =====================================================
    # Accessories Sheet
    # =====================================================
    accessories = data.get("accessories", {})

    rows = [
        ["Total Accessory Units", accessories.get("total_units", 0)],
        ["Currently Assigned Units", accessories.get("assigned_units", 0)],
        ["Available Units", accessories.get("available_units", 0)],
        [
            "Utilization % (Assigned ÷ Total Units)",
            accessories.get("utilization_percent", 0),
        ],
        [
            "Damage Events (Last 30 Days)",
            accessories.get("damage_events_last_30_days", 0),
        ],
        ["Units Reported Lost", accessories.get("lost_units", 0)],
    ]

    spec["Accessories"] = {
        "headers": ["Metric", "Value"],
        "rows": rows,
    }

    # =====================================================
    # Consumables Sheet
    # =====================================================
    consumables = data.get("consumables", {})

    rows = [
        ["Total Units In Stock", consumables.get("total_units_in_stock", 0)],
        [
            "Units Currently Issued To Users",
            consumables.get("active_issued_quantity", 0),
        ],
        [
            "Available Units On Hand",
            consumables.get("available_quantity", 0),
        ],
        [
            "Low Stock Items (At / Below Threshold)",
            consumables.get("low_stock_items", 0),
        ],
        ["Out Of Stock Items", consumables.get("out_of_stock_items", 0)],
    ]

    spec["Consumables"] = {
        "headers": ["Metric", "Value"],
        "rows": rows,
    }

    # =====================================================
    # Users Sheet
    # =====================================================
    users = data.get("users", {})

    rows = [
        ["Total Users In Scope", users.get("total", 0)],
        ["Active User Accounts", users.get("active", 0)],
        ["Inactive User Accounts", users.get("inactive", 0)],
        ["Locked User Accounts", users.get("locked", 0)],
    ]

    spec["Users"] = {
        "headers": ["Metric", "Value"],
        "rows": rows,
    }

    # =====================================================
    # Roles Sheet
    # =====================================================
    roles = data.get("roles", {})

    if roles:
        rows = [
            [role.replace("_", " ").title(), count]
            for role, count in roles.items()
        ]
    else:
        rows = [["No Roles Within Selected Scope", ""]]

    spec["Roles"] = {
        "headers": ["Role Type", "Assigned Count"],
        "rows": rows,
    }

    # =====================================================
    # Breakdown Sheet
    # =====================================================
    breakdown = data.get("breakdown", [])

    if breakdown:
        rows = []

        for row in breakdown:
            rows.append([
                str(row.get("scope_type", "")).title(),
                row.get("scope_name"),
                row.get("equipment", 0),
                row.get("assigned_equipment", 0),
                row.get("damaged_equipment", 0),
                row.get("under_repair", 0),
                row.get("accessory_units", 0),
                row.get("consumable_units", 0),
                row.get("low_stock_consumables", 0),
                row.get("users", 0),
                row.get("active_users", 0),
            ])

        spec["Breakdown"] = {
            "headers": [
                "Scope Type",
                "Scope Name",
                "Equipment Records",
                "Assigned Equipment",
                "Damaged Equipment",
                "Under Repair",
                "Accessory Units",
                "Consumable Units",
                "Low Stock Consumables",
                "Users In Scope",
                "Active Users",
            ],
            "rows": rows,
        }

    return spec