
def site_asset_to_workbook_spec(payload: dict) -> dict:
    meta = payload["meta"]
    data = payload["data"]

    summary = data["summary"]
    tables = data["tables"]

    spec = {}

    # ---------------------------------
    # Report Info
    # ---------------------------------
    spec["Report Info"] = {
        "headers": ["Field", "Value"],
        "rows": [
            ["Report Name", meta["report_name"]],
            ["Generated At", meta["generated_at"]],
            ["Generated By", meta["generated_by"]],
            ["Site Type", meta["site_type"]],
            ["Site ID", meta["site_id"]],
            ["Site Name", meta["site_name"]],
        ],
    }

    # ---------------------------------
    # Summary
    # Only show metrics actually returned
    # ---------------------------------
    label_map = {
        "equipment_count": "Equipment Count",
        "component_count": "Component Count",
        "consumable_count": "Consumable Count",
        "accessory_count": "Accessory Count",
        "grand_total": "Grand Total",
    }

    spec["Summary"] = {
        "headers": ["Metric", "Value"],
        "rows": [
            [label_map.get(key, key.replace("_", " ").title()), value]
            for key, value in summary.items()
        ],
    }

    # ---------------------------------
    # Asset Sheets
    # Only selected asset types exist in tables
    # ---------------------------------
    for sheet_name, rows in tables.items():

        if rows:
            headers = list(rows[0].keys())
            body = [[row.get(h) for h in headers] for row in rows]
        else:
            headers = ["Message"]
            body = [["No records found"]]

        spec[sheet_name] = {
            "headers": headers,
            "rows": body,
        }

    return spec

def site_audit_log_to_workbook_spec(payload: dict) -> dict:
    if not payload:
        raise ValueError("Empty audit log payload")

    spec = {}

    meta = payload["meta"]
    data = payload["data"]

    summary = data["summary"]
    logs = data["tables"].get("Audit Logs", [])

    # -----------------------------
    # Report Info
    # -----------------------------
    spec["Report Info"] = {
        "headers": ["Field", "Value"],
        "rows": [
            ["Generated At", meta.get("generated_at", "N/A")],
            ["Generated By", meta.get("generated_by", "N/A")],
            ["Site Type", meta.get("site_type", "N/A")],
            ["Site ID", meta.get("site_id", "N/A")],
            ["Site Name", meta.get("site_name", "N/A")],
            ["Audit Period (days)", meta.get("audit_period_days", "N/A")],
            ["Total Events", summary.get("log_count", 0)],
        ],
    }

    # -----------------------------
    # Audit Logs
    # -----------------------------
    if logs:
        headers = list(logs[0].keys())
        rows = [[row.get(h) for h in headers] for row in logs]
    else:
        headers = ["Message"]
        rows = [[
            "No audit log entries were found for the selected site and time period."
        ]]

    spec["Audit Logs"] = {
        "headers": headers,
        "rows": rows,
    }

    return spec