from django.utils import timezone

def user_summary_to_workbook_spec(payload: dict) -> dict:
    if not payload:
        raise ValueError("Empty user summary payload")

    spec = {}

    meta = payload.get("meta", {})
    data = payload.get("data", {})

    # --------------------
    # Demographics
    # --------------------
    demographics = data.get("demographics")
    if demographics:
        rows = [
            [key.replace("_", " ").title(), value]
            for key, value in demographics.items()
        ]
    else:
        rows = [["Message", "No demographic data available."]]

    spec["Demographics"] = {
        "headers": ["Field", "Value"],
        "rows": rows,
    }

    # --------------------
    # Login Stats
    # --------------------
    login_stats = data.get("loginStats")
    if login_stats:
        spec["Login Stats"] = {
            "headers": list(login_stats.keys()),
            "rows": [list(login_stats.values())],
        }
    else:
        spec["Login Stats"] = {
            "headers": ["Message"],
            "rows": [["No login statistics available."]],
        }

    # --------------------
    # Audit Summary
    # --------------------
    audit_summary = data.get("auditSummary")
    if audit_summary:
        rows = [["Total Events", audit_summary.get("total", 0)]]

        for event, count in audit_summary.get("events", {}).items():
            rows.append([event, count])
    else:
        rows = [["No audit events found for this user.", ""]]

    spec["Audit Summary"] = {
        "headers": ["Metric", "Count"],
        "rows": rows,
    }

    # --------------------
    # Role Summary
    # --------------------
    role_summary = data.get("roleSummary")
    if role_summary:
        rows = [
            [
                r.get("role_name"),
                r.get("scope"),
                r.get("assigned_date"),
            ]
            for r in role_summary
        ]
        headers = ["Role", "Scope", "Assigned Date"]
    else:
        headers = ["Message"]
        rows = [["No roles assigned to this user."]]

    spec["Role Summary"] = {
        "headers": headers,
        "rows": rows,
    }

    # --------------------
    # Password Events
    # --------------------
    password_events = data.get("passwordevents")
    if password_events:
        rows = [
            [
                "Total password reset events",
                password_events.get("total_password_reset_events", 0),
            ],
            [
                "Active reset tokens",
                password_events.get("active_reset_tokens", 0),
            ],
        ]
    else:
        rows = [["Message", "No password-related events recorded."]]

    spec["Password Events"] = {
        "headers": ["Metric", "Value"],
        "rows": rows,
    }

    return spec

def user_audit_history_to_workbook_spec(payload: dict) -> dict:
    """
    Convert canonical user audit history payload into workbook spec.

    Expected payload:

    {
        "meta": {...},
        "data": {
            "summary": {...},
            "history_rows": [...]
        }
    }
    """

    if not payload:
        raise ValueError("Empty user audit history payload")

    spec = {}

    meta = payload["meta"]
    data = payload["data"]

    summary = data.get("summary", {})
    history = data.get("history_rows", [])

    # -------------------------------------------------
    # Sheet 1: Report Info
    # -------------------------------------------------

    spec["Report Info"] = {
        "headers": ["Field", "Value"],
        "rows": [
            ["Report Name", meta.get("report_name")],
            ["Generated By", meta.get("generated_by")],
            ["Generated At", meta.get("generated_at")],
            ["User Public ID", meta.get("user_public_id")],
            ["User Email", meta.get("user_email")],
            ["User Full Name", meta.get("user_full_name")],
            ["Start Date", meta.get("start_date")],
            ["End Date", meta.get("end_date")],
        ],
    }

    # -------------------------------------------------
    # Sheet 2: Audit Stats
    # -------------------------------------------------

    if summary:
        rows = [
            [event_type, count]
            for event_type, count in summary.items()
        ]
    else:
        rows = [["No audit events recorded for this user.", ""]]

    spec["Audit Stats"] = {
        "headers": ["Event Type", "Count"],
        "rows": rows,
    }

    # -------------------------------------------------
    # Sheet 3: History
    # -------------------------------------------------

    if history:
        rows = history
    else:
        rows = [[
            "No audit history found for this user.",
            "", "", "", "", "", "", "", "", "", ""
        ]]

    spec["History"] = {
        "headers": [
            "Timestamp",
            "Event Type",
            "Description",
            "Target Model",
            "Target ID",
            "Target Name",
            "Department",
            "Location",
            "Room",
            "IP Address",
            "User Agent",
        ],
        "rows": rows,
    }

    return spec


def user_login_history_to_workbook_spec(payload: dict) -> dict:
    """
    Convert canonical user login history payload into workbook spec.
    """

    if not payload:
        raise ValueError("Empty login history payload")

    spec = {}

    meta = payload["meta"]
    data = payload["data"]

    # ---------------------------------
    # Summary Sheet
    # ---------------------------------

    summary = data.get("summary_stats", {})

    rows = [
        ["Report Name", meta.get("report_name")],
        ["Generated At", meta.get("generated_at")],
        ["Generated By", meta.get("generated_by")],
        ["Target User Public ID", meta.get("user_public_id")],
        ["Target User Email", meta.get("user_email")],
        ["Target User Full Name", meta.get("user_full_name")],
        ["Start Date", meta.get("start_date")],
        ["End Date", meta.get("end_date")],
        [],
        ["Metric", "Value"],
    ]

    for key, value in summary.items():
        rows.append([
            key.replace("_", " ").title(),
            value,
        ])

    spec["Summary"] = {
        "headers": [],
        "rows": rows,
    }

    # ---------------------------------
    # Session Stats
    # ---------------------------------

    session_stats = data.get("session_stats", {})

    spec["Session Stats"] = {
        "headers": ["Metric", "Value"],
        "rows": [
            [
                key.replace("_", " ").title(),
                value,
            ]
            for key, value in session_stats.items()
        ],
    }

    # ---------------------------------
    # Login History
    # ---------------------------------

    history = data.get("login_history", [])

    spec["Login History"] = {
        "headers": [
            "Timestamp",
            "Event Type",
            "Description",
            "IP Address",
            "User Agent",
            "Department",
            "Location",
            "Room",
        ],
        "rows": [
            [
                row.get("timestamp"),
                row.get("event_type"),
                row.get("description"),
                row.get("ip_address"),
                row.get("user_agent"),
                row.get("department"),
                row.get("location"),
                row.get("room"),
            ]
            for row in history
        ],
    }

    # ---------------------------------
    # IP Breakdown
    # ---------------------------------

    spec["IP Breakdown"] = {
        "headers": [
            "IP Address",
            "Login Count",
            "First Seen",
            "Last Seen",
        ],
        "rows": [
            [
                row.get("ip_address"),
                row.get("count"),
                row.get("first_seen"),
                row.get("last_seen"),
            ]
            for row in data.get("ip_breakdown", [])
        ],
    }

    # ---------------------------------
    # Device Breakdown
    # ---------------------------------

    spec["Device Breakdown"] = {
        "headers": ["User Agent", "Login Count"],
        "rows": [
            [
                row.get("user_agent"),
                row.get("count"),
            ]
            for row in data.get("device_breakdown", [])
        ],
    }

    # ---------------------------------
    # Login Timeline
    # ---------------------------------

    spec["Login Timeline"] = {
        "headers": ["Date", "Login Count"],
        "rows": [
            [
                row.get("day"),
                row.get("count"),
            ]
            for row in data.get("login_timeline", [])
        ],
    }

    return spec