# Generated by Django 5.2.12 on 2026-04-16 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('report_type', models.CharField(choices=[('user_summary', 'User Summary'), ('site_assets', 'Site Assets'), ('site_audit_logs', 'Site Audit Logs'), ('asset_import', 'Asset Import'), ('user_audit_history', 'User Audit History'), ('user_login_history', 'User Login History'), ('asset_history', 'Asset History')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('params', models.JSONField()),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('report_file', models.CharField(blank=True, max_length=500)),
                ('result_payload', models.JSONField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='reporting_r_user_id_63fdca_idx'), models.Index(fields=['user', 'report_type'], name='reporting_r_user_id_33830b_idx'), models.Index(fields=['created_at'], name='reporting_r_created_4a3b0a_idx')],
            },
        ),
    ]
