# Generated by Django 5.2.12 on 2026-04-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['user', 'status'], name='reporting_r_user_id_63fdca_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['user', 'report_type'], name='reporting_r_user_id_33830b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportjob',
            index=models.Index(fields=['created_at'], name='reporting_r_created_4a3b0a_idx'),
        ),
    ]
