# Generated by Django 5.2.12 on 2026-04-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_reportjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('user_summary', 'User Summary'), ('site_assets', 'Site Assets'), ('site_audit_logs', 'Site Audit Logs'), ('asset_import', 'Asset Import'), ('user_audit_history', 'User Audit History'), ('user_login_history', 'User Login History'), ('asset_history', 'Asset History'), ('inventory_summary', 'Inventory Summary')], db_index=True, max_length=40),
        ),
    ]
