# Generated by Django 5.2.12 on 2026-04-19 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_change', models.IntegerField()),
                ('event_type', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('used', 'Used'), ('lost', 'Lost'), ('condemned', 'Condemned'), ('restocked', 'Restocked'), ('adjusted', 'Adjusted'), ('return_requested', 'Return Requested')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_change', models.IntegerField()),
                ('event_type', models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('condemned', 'Condemned'), ('restocked', 'Restocked'), ('adjusted', 'Adjusted'), ('return_requested', 'Return Requested')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Remaining quantity currently held by the user')),
                ('issued_quantity', models.PositiveIntegerField(help_text='Original quantity issued in this batch')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When consumables were issued to the user')),
                ('returned_at', models.DateTimeField(blank=True, help_text='Set when all remaining quantity is returned or consumed', null=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('repaired', 'Repaired'), ('retired', 'Retired'), ('under_repair', 'Under repair'), ('condemned', 'Condemned'), ('return_requested', 'Return Requested')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('partial', 'Partial'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('item_type', models.CharField(choices=[('equipment', 'Equipment'), ('accessory', 'Accessory'), ('consumable', 'Consumable')], db_index=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.accessory')),
            ],
        ),
    ]
