# Generated by Django 5.2.12 on 2026-04-19 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '__first__'),
        ('assignments', '0001_initial'),
        ('sites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessoryassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessoryevent',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assets.accessory'),
        ),
        migrations.AddField(
            model_name='accessoryevent',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_accessory_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessoryevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableevent',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assets.consumable'),
        ),
        migrations.AddField(
            model_name='consumableevent',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_consumable_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consumables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='assets.consumable'),
        ),
        migrations.AddField(
            model_name='consumableissue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumable_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumableevent',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='assignments.consumableissue'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_assignment', to='assets.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentevent',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assets.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentevent',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_equipment_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='accessory_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.accessoryassignment'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='consumable_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.consumableissue'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='equipment_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.equipmentassignment'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assignments.returnrequest'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.room'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consumableissue',
            index=models.Index(fields=['consumable', 'user'], name='assignments_consuma_1c7cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='consumableissue',
            index=models.Index(fields=['user', 'returned_at'], name='assignments_user_id_765043_idx'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('consumable', 'user'), name='unique_open_issue_per_user_consumable'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='consumable_issue_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('issued_quantity__gt', 0)), name='consumable_issue_issued_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__lte', models.F('issued_quantity'))), name='consumable_issue_quantity_lte_issued'),
        ),
        migrations.AddConstraint(
            model_name='consumableissue',
            constraint=models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('quantity', 0), _connector='OR'), name='consumable_issue_closed_has_zero_quantity'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='assignments_status_46c524_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['requested_at'], name='assignments_request_25d464_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['item_type'], name='assignments_item_ty_b3b586_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['equipment_assignment'], name='assignments_equipme_3ee39a_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['accessory_assignment'], name='assignments_accesso_0e9bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['consumable_issue'], name='assignments_consuma_03242e_idx'),
        ),
    ]
