# Generated by Django 5.2.12 on 2026-04-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('db_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryassignment',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='db_inventory.accessory'),
        ),
    ]
