# Generated by Django 5.2.12 on 2026-05-23 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0005_remove_agreementhistory_agreement_and_more'),
        ('sites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('agreement_type', models.CharField(choices=[('LICENSE', 'License'), ('WARRANTY', 'Warranty'), ('SERVICE', 'Service'), ('MAINTENANCE', 'Maintenance'), ('SUPPORT', 'Support'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=20)),
                ('vendor', models.CharField(db_index=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('managing_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_agreements', to='sites.department')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('RENEWED', 'Renewed'), ('EXTENDED', 'Extended'), ('TERMINATED', 'Terminated'), ('STATUS_CHANGED', 'Status Changed')], db_index=True, max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('previous_expiry_date', models.DateField(blank=True, null=True)),
                ('new_expiry_date', models.DateField(blank=True, null=True)),
                ('previous_renewal_date', models.DateField(blank=True, null=True)),
                ('new_renewal_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_history', to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='agreements.assetagreement')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('DEPARTMENT', 'Department'), ('LOCATION', 'Location'), ('ROOM', 'Room')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_coverages', to='sites.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_coverages', to='sites.location')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_coverages', to='sites.room')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='agreements.assetagreement')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAgreementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('coverage_start', models.DateField(blank=True, null=True)),
                ('coverage_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset_name_snapshot', models.CharField(default='', editable=False, max_length=150)),
                ('asset_serial_snapshot', models.CharField(blank=True, default='', editable=False, max_length=150)),
                ('asset_public_id_snapshot', models.CharField(default='', editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='assets.accessory')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agreements.assetagreement')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='assets.consumable')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_items', to='assets.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ATTACHED', 'Attached'), ('REMOVED', 'Removed'), ('INVALIDATED', 'Invalidated'), ('REINSTATED', 'Reinstated'), ('COVERAGE_EXPIRED', 'Coverage Expired')], db_index=True, max_length=30)),
                ('asset_public_id', models.CharField(db_index=True, max_length=50)),
                ('asset_name', models.CharField(max_length=150)),
                ('asset_serial', models.CharField(blank=True, max_length=150)),
                ('asset_type', models.CharField(max_length=30)),
                ('coverage_start', models.DateField(blank=True, null=True)),
                ('coverage_end', models.DateField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('room_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_item_history', to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_history', to='agreements.assetagreement')),
                ('agreement_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='agreements.assetagreementitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['public_id'], name='agreements__public__cd7a90_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['name'], name='agreements__name_a392fd_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['agreement_type'], name='agreements__agreeme_a9fdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['status'], name='agreements__status_6c7fda_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreement',
            index=models.Index(fields=['vendor'], name='agreements__vendor_db46fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('expiry_date__gte', models.F('start_date')), _connector='OR'), name='agreement_expiry_after_start'),
        ),
        migrations.AddConstraint(
            model_name='assetagreement',
            constraint=models.CheckConstraint(condition=models.Q(('renewal_date__isnull', True), ('expiry_date__isnull', True), ('renewal_date__lte', models.F('expiry_date')), _connector='OR'), name='agreement_renewal_before_expiry'),
        ),
        migrations.AddIndex(
            model_name='agreementcoverage',
            index=models.Index(fields=['public_id'], name='agreements__public__03688e_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementcoverage',
            index=models.Index(fields=['scope_type'], name='agreements__scope_t_ee5073_idx'),
        ),
        migrations.AddConstraint(
            model_name='agreementcoverage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_type', 'GLOBAL'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', True)), models.Q(('scope_type', 'DEPARTMENT'), ('department__isnull', False), ('location__isnull', True), ('room__isnull', True)), models.Q(('scope_type', 'LOCATION'), ('department__isnull', True), ('location__isnull', False), ('room__isnull', True)), models.Q(('scope_type', 'ROOM'), ('department__isnull', True), ('location__isnull', True), ('room__isnull', False)), _connector='OR'), name='valid_agreement_coverage_scope'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['public_id'], name='agreements__public__cd406b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['coverage_start'], name='agreements__coverag_09ca22_idx'),
        ),
        migrations.AddIndex(
            model_name='assetagreementitem',
            index=models.Index(fields=['coverage_end'], name='agreements__coverag_36c386_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equipment__isnull', False), ('consumable__isnull', True), ('accessory__isnull', True)), models.Q(('equipment__isnull', True), ('consumable__isnull', False), ('accessory__isnull', True)), models.Q(('equipment__isnull', True), ('consumable__isnull', True), ('accessory__isnull', False)), _connector='OR'), name='agreement_item_single_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_end__isnull', True), ('coverage_start__isnull', True), ('coverage_end__gte', models.F('coverage_start')), _connector='OR'), name='agreement_item_valid_coverage_dates'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.CheckConstraint(condition=models.Q(('equipment__isnull', True), ('quantity', 1), _connector='OR'), name='equipment_agreement_quantity_one'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('agreement', 'equipment'), name='unique_equipment_agreement_item'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('consumable__isnull', False)), fields=('agreement', 'consumable'), name='unique_consumable_agreement_item'),
        ),
        migrations.AddConstraint(
            model_name='assetagreementitem',
            constraint=models.UniqueConstraint(condition=models.Q(('accessory__isnull', False)), fields=('agreement', 'accessory'), name='unique_accessory_agreement_item'),
        ),
        migrations.AddIndex(
            model_name='agreementitemhistory',
            index=models.Index(fields=['event_type'], name='agreements__event_t_593d61_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementitemhistory',
            index=models.Index(fields=['asset_public_id'], name='agreements__asset_p_5ea7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementitemhistory',
            index=models.Index(fields=['created_at'], name='agreements__created_5e06ae_idx'),
        ),
    ]
