# Generated by Django 5.2.12 on 2026-05-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
        ('sites', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agreementcoverage',
            index=models.Index(fields=['scope_type', 'department'], name='agreements__scope_t_b9fdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementcoverage',
            index=models.Index(fields=['scope_type', 'location'], name='agreements__scope_t_b888f1_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementcoverage',
            index=models.Index(fields=['scope_type', 'room'], name='agreements__scope_t_0e6fcd_idx'),
        ),
    ]
