# Generated by Django 5.2.14 on 2026-06-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreementcoverage_agreements__scope_t_b9fdfe_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementhistory',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('RENEWED', 'Renewed'), ('EXTENDED', 'Extended'), ('TERMINATED', 'Terminated'), ('STATUS_CHANGED', 'Status Changed'), ('EXPIRED', 'Expired')], db_index=True, max_length=30),
        ),
    ]
