from rest_framework.viewsets import ReadOnlyModelViewSet
from rest_framework.decorators import action
from django.utils.dateparse import parse_date
from django.utils import timezone
import io
from openpyxl import Workbook
from db_inventory.models import Equipment, Component, Consumable, Accessory
from django.db.models import Q


class TimeSeriesViewset(ReadOnlyModelViewSet):
    """Base class for returning date-based metrics suitable for graphs."""

    date_field = "date"  # override in child classes

    def filter_queryset_by_date(self, qs):
        start = self.request.query_params.get("start")
        end = self.request.query_params.get("end")

        if start:
            qs = qs.filter(**{f"{self.date_field}__gte": parse_date(start)})
        if end:
            qs = qs.filter(**{f"{self.date_field}__lte": parse_date(end)})

        return qs.order_by(self.date_field)

    @action(detail=False, methods=["get"])
    def timeseries(self, request):
        """Return all numeric fields as arrays for chart rendering."""
        qs = self.filter_queryset_by_date(self.get_queryset())

        if not qs.exists():
            return Response({"labels": [], "data": {} })

        labels = [getattr(i, self.date_field).isoformat() for i in qs]

        # Include only integer fields
        fields = [
            f.name for f in qs.model._meta.get_fields()
            if f.get_internal_type() in ("IntegerField", "PositiveIntegerField")
        ]

        data = {field: [getattr(i, field) for i in qs] for field in fields}

        return Response({
            "labels": labels,
            "data": data
        })


    
def build_site_filter(site_type, site_obj, model_class):
    if site_type == "department":
        if model_class == Equipment:
            return Q(room__location__department=site_obj)

        if model_class in [Accessory, Consumable]:
            return Q(room__location__department=site_obj)

        if model_class == Component:
            return Q(equipment__room__location__department=site_obj)

    elif site_type == "location":
        if model_class == Equipment:
            return Q(room__location=site_obj)

        if model_class in [Accessory, Consumable]:
            return Q(room__location=site_obj)

        if model_class == Component:
            return Q(equipment__room__location=site_obj)

    elif site_type == "room":
        if model_class == Equipment:
            return Q(room=site_obj)

        if model_class in [Accessory, Consumable]:
            return Q(room=site_obj)

        if model_class == Component:
            return Q(equipment__room=site_obj)

    raise ValueError(
        f"Unsupported site_type={site_type} or model={model_class.__name__}"
    )


def generate_site_asset_excel(
    site_type,
    site_obj,
    asset_types,
    generated_by=None,
):
    wb = Workbook()
    wb.remove(wb.active)

    asset_model_map = {
        'equipment': {
            'model': Equipment,
            'fields': ['name', 'brand', 'model', 'serial_number', 'public_id']
        },
        'component': {
            'model': Component,
            'fields': ['name', 'brand', 'model', 'serial_number', 'quantity', 'public_id', 'equipment_id']
        },
        'consumable': {
            'model': Consumable,
            'fields': ['name', 'description', 'quantity', 'public_id', 'room_id']
        },
        'accessory': {
            'model': Accessory,
            'fields': ['name', 'serial_number', 'quantity', 'public_id', 'room_id']
        }
    }

    generated_at = timezone.now()
    asset_totals = {}
    asset_querysets = {}

    # 1️⃣ Build querysets & totals FIRST
    for asset_type in asset_types:
        asset_info = asset_model_map.get(asset_type)
        if not asset_info:
            continue

        model = asset_info['model']
        qs = model.objects.filter(
            build_site_filter(site_type, site_obj, model)
        )

        asset_querysets[asset_type] = qs
        asset_totals[asset_type] = qs.count()

    # 2️⃣ Create Report Info sheet
    info_sheet = wb.create_sheet(title="Report Info")

    info_rows = [
        ("Generated At", generated_at.strftime("%Y-%m-%d %H:%M:%S")),
        ("Generated By", generated_by.get_username() if generated_by else "System"),
        ("Site Type", site_type.capitalize()),
        ("Site ID", site_obj.public_id),
        ("", ""),
        ("Asset Totals", ""),
    ]

    for row in info_rows:
        info_sheet.append(row)

    for asset_type, total in asset_totals.items():
        info_sheet.append([asset_type.capitalize(), total])

    # 3️⃣ Create asset sheets
    for asset_type, qs in asset_querysets.items():
        asset_info = asset_model_map[asset_type]
        fields = asset_info['fields']

        sheet = wb.create_sheet(title=asset_type.capitalize())
        sheet.append(fields)

        for obj in qs:
            row = []
            for field in fields:
                if field == 'equipment_id':
                    value = obj.equipment.public_id if obj.equipment else ''
                elif field == 'room_id':
                    value = obj.room.public_id if obj.room else ''
                else:
                    value = getattr(obj, field, '')
                row.append(value)
            sheet.append(row)

    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    return output
