# Generated by Django 5.2.15 on 2026-06-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('is_system', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('scope_type', models.CharField(choices=[('ROOM', 'Room'), ('LOCATION', 'Location'), ('DEPARTMENT', 'Department'), ('GLOBAL', 'Global')], max_length=20)),
                ('level', models.PositiveIntegerField(default=0)),
                ('is_system_role', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='authorization.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
