# Generated by Django 5.2.15 on 2026-06-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level', 'name']},
        ),
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(db_index=True, default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module'], name='authorizati_module_3133bf_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['is_system'], name='authorizati_is_syst_112c84_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='authorizati_code_0b327f_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['scope_type'], name='authorizati_scope_t_563de1_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['level'], name='authorizati_level_10c6db_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system_role'], name='authorizati_is_syst_818c8d_idx'),
        ),
    ]
