# Generated by Django 5.2.12 on 2026-04-16 04:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('img_link', models.URLField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['public_id'], name='sites_depar_public__7b4858_idx'), models.Index(fields=['name'], name='sites_depar_name_0b0d53_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='sites.department')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='sites.location')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, db_index=True, editable=False, max_length=32, unique=True)),
                ('is_current', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_placements', to='sites.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Room',
                'verbose_name_plural': 'User Rooms',
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['public_id'], name='sites_locat_public__706c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='sites_locat_name_d93afd_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_location_name_per_department'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['public_id'], name='sites_room_public__f29a77_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='sites_room_name_250e08_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_room_name_per_location'),
        ),
        migrations.AddIndex(
            model_name='userplacement',
            index=models.Index(fields=['public_id'], name='sites_userp_public__c07241_idx'),
        ),
        migrations.AddIndex(
            model_name='userplacement',
            index=models.Index(fields=['user'], name='sites_userp_user_id_4c3bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='userplacement',
            index=models.Index(fields=['is_current'], name='sites_userp_is_curr_fb6836_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='unique_current_location_per_user'),
        ),
        migrations.AddConstraint(
            model_name='userplacement',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('room__isnull', False), _connector='OR'), name='current_user_location_requires_room'),
        ),
    ]
