# Generated by Django 5.2.12 on 2026-04-18 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userplacement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['public_id'], name='sites_locat_public__706c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='sites_locat_name_d93afd_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_location_name_per_department'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['public_id'], name='sites_room_public__f29a77_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='sites_room_name_250e08_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_room_name_per_location'),
        ),
        migrations.AddIndex(
            model_name='userplacement',
            index=models.Index(fields=['public_id'], name='sites_userp_public__c07241_idx'),
        ),
        migrations.AddIndex(
            model_name='userplacement',
            index=models.Index(fields=['user'], name='sites_userp_user_id_4c3bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='userplacement',
            index=models.Index(fields=['is_current'], name='sites_userp_is_curr_fb6836_idx'),
        ),
        migrations.AddConstraint(
            model_name='userplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='unique_current_location_per_user'),
        ),
        migrations.AddConstraint(
            model_name='userplacement',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('room__isnull', False), _connector='OR'), name='current_user_location_requires_room'),
        ),
    ]
