
def site_asset_to_workbook_spec(payload: dict) -> dict:
    spec = {}

    meta = payload["meta"]

    # -----------------------------
    # Report Info
    # -----------------------------
    spec["Report Info"] = {
        "headers": ["Field", "Value"],
        "rows": [
            ["Generated At", meta["generated_at"]],
            ["Generated By", meta["generated_by"]],
            ["Site Type", meta["site_type"]],
            ["Site ID", meta["site_id"]],
            ["Site Name", meta["site_name"]],
        ],
    }

    # -----------------------------
    # Asset sheets
    # -----------------------------
    for asset_type, rows in payload["data"]["assets"].items():
        if rows:
            headers = list(rows[0].keys())
            data_rows = [
                [row.get(h) for h in headers]
                for row in rows
            ]
        else:
            headers = ["Message"]
            data_rows = [[
                f"No {asset_type.replace('_', ' ')} records found for this site."
            ]]

        spec[asset_type.capitalize()] = {
            "headers": headers,
            "rows": data_rows,
        }

    return spec

def site_audit_log_to_workbook_spec(payload: dict) -> dict:
    if not payload:
        raise ValueError("Empty audit log payload")

    spec = {}

    meta = payload["meta"]
    logs = payload["data"]["logs"]

    # -----------------------------
    # Report Info
    # -----------------------------
    spec["Report Info"] = {
        "headers": ["Field", "Value"],
        "rows": [
            ["Generated At", meta["generated_at"]],
            ["Generated By", meta["generated_by"]],
            ["Site Type", meta["site_type"]],
            ["Site ID", meta["site_id"]],
            ["Site Name", meta["site_name"]],
            ["Audit Period (days)", meta["audit_period_days"]],
            ["Total Events", len(logs)],
        ],
    }

    # -----------------------------
    # Audit Logs
    # -----------------------------
    if logs:
        headers = list(logs[0].keys())
        rows = [[row.get(h) for h in headers] for row in logs]
    else:
        headers = ["Message"]
        rows = [[
            "No audit log entries were found for the selected site and time period."
        ]]

    spec["Audit Logs"] = {
        "headers": headers,
        "rows": rows,
    }

    return spec