
def site_asset_to_workbook_spec(payload: dict) -> dict:
    spec = {}

    meta = payload["meta"]

    spec["Report Info"] = {
        "headers": ["Field", "Value"],
        "rows": [
            ["Generated At", meta["generated_at"]],
            ["Generated By", meta["generated_by"]],
            ["Site Type", meta["site_type"]],
            ["Site ID", meta["site_id"]],
            ["Site Name", meta["site_name"]],
        ],
    }

    for asset_type, rows in payload["assets"].items():
        if rows:
            headers = list(rows[0].keys())
        else:
            # still render the sheet, but with no rows
            headers = []

        spec[asset_type.capitalize()] = {
            "headers": headers,
            "rows": [
                [row.get(h) for h in headers]
                for row in rows
            ],
        }

    return spec