def user_summary_to_workbook_spec(payload: dict) -> dict:
    if not payload:
        raise ValueError("Empty user summary payload")

    spec = {}

    meta = payload.get("meta", {})
    data = payload.get("data", {})

    # --------------------
    # Demographics
    # --------------------
    demographics = data.get("demographics")
    if demographics:
        rows = [
            [key.replace("_", " ").title(), value]
            for key, value in demographics.items()
        ]
    else:
        rows = [["Message", "No demographic data available."]]

    spec["Demographics"] = {
        "headers": ["Field", "Value"],
        "rows": rows,
    }

    # --------------------
    # Login Stats
    # --------------------
    login_stats = data.get("loginStats")
    if login_stats:
        spec["Login Stats"] = {
            "headers": list(login_stats.keys()),
            "rows": [list(login_stats.values())],
        }
    else:
        spec["Login Stats"] = {
            "headers": ["Message"],
            "rows": [["No login statistics available."]],
        }

    # --------------------
    # Audit Summary
    # --------------------
    audit_summary = data.get("auditSummary")
    if audit_summary:
        rows = [["Total Events", audit_summary.get("total", 0)]]

        for event, count in audit_summary.get("events", {}).items():
            rows.append([event, count])
    else:
        rows = [["No audit events found for this user.", ""]]

    spec["Audit Summary"] = {
        "headers": ["Metric", "Count"],
        "rows": rows,
    }

    # --------------------
    # Role Summary
    # --------------------
    role_summary = data.get("roleSummary")
    if role_summary:
        rows = [
            [
                r.get("role_name"),
                r.get("scope"),
                r.get("assigned_date"),
            ]
            for r in role_summary
        ]
        headers = ["Role", "Scope", "Assigned Date"]
    else:
        headers = ["Message"]
        rows = [["No roles assigned to this user."]]

    spec["Role Summary"] = {
        "headers": headers,
        "rows": rows,
    }

    # --------------------
    # Password Events
    # --------------------
    password_events = data.get("passwordevents")
    if password_events:
        rows = [
            ["Total password reset events", password_events.get("total_password_reset_events", 0)],
            ["Active reset tokens", password_events.get("active_reset_tokens", 0)],
        ]
    else:
        rows = [["Message", "No password-related events recorded."]]

    spec["Password Events"] = {
        "headers": ["Metric", "Value"],
        "rows": rows,
    }

    return spec

def user_audit_history_to_workbook_spec(payload: dict) -> dict:
    """
    Convert user audit history payload into workbook spec.

    Expected payload structure:

    {
        meta: {...},
        data: {
            report_info: {...},
            audit_stats: {...},
            history: [...]
        }
    }
    """

    if not payload:
        raise ValueError("Empty user audit history payload")

    spec = {}

    data = payload.get("data", {})

    report_info = data.get("report_info", {})
    audit_stats = data.get("audit_stats", {})
    history = data.get("history_rows", [])

    # -------------------------------------------------
    # Sheet 1: Report Info
    # -------------------------------------------------

    if report_info:
        rows = [
            ["Generated By", report_info.get("generated_by")],
            ["Generated At", report_info.get("generated_at")],
            ["User Public ID", report_info.get("user_public_id")],
            ["User Email", report_info.get("user_email")],
            ["User Full Name", report_info.get("user_full_name")],
            ["Start Date", report_info.get("start_date")],
            ["End Date", report_info.get("end_date")],
            ["Total Events", report_info.get("total_events")],
        ]
    else:
        rows = [["Message", "No report metadata available."]]

    spec["Report Info"] = {
        "headers": ["Field", "Value"],
        "rows": rows,
    }

    # -------------------------------------------------
    # Sheet 2: Audit Stats
    # -------------------------------------------------

    if audit_stats:
        rows = [[event_type, count] for event_type, count in audit_stats.items()]
    else:
        rows = [["No audit events recorded for this user.", ""]]

    spec["Audit Stats"] = {
        "headers": ["Event Type", "Count"],
        "rows": rows,
    }

    # -------------------------------------------------
    # Sheet 3: History
    # -------------------------------------------------

    if history:
        rows = history
    else:
        rows = [["No audit history found for this user.", ""]]

    spec["History"] = {
        "headers": [
            "Timestamp",
            "Event Type",
            "Description",
            "Target Model",
            "Target ID",
            "Target Name",
            "Department",
            "Location",
            "Room",
            "IP Address",
            "User Agent",
        ],
        "rows": rows,
    }

    return spec