from django.utils import timezone

def user_summary_to_workbook_spec(payload: dict) -> dict:
    if not payload:
        raise ValueError("Empty user summary payload")

    spec = {}

    meta = payload.get("meta", {})
    data = payload.get("data", {})

    # --------------------
    # Demographics
    # --------------------
    demographics = data.get("demographics")
    if demographics:
        rows = [
            [key.replace("_", " ").title(), value]
            for key, value in demographics.items()
        ]
    else:
        rows = [["Message", "No demographic data available."]]

    spec["Demographics"] = {
        "headers": ["Field", "Value"],
        "rows": rows,
    }

    # --------------------
    # Login Stats
    # --------------------
    login_stats = data.get("loginStats")
    if login_stats:
        spec["Login Stats"] = {
            "headers": list(login_stats.keys()),
            "rows": [list(login_stats.values())],
        }
    else:
        spec["Login Stats"] = {
            "headers": ["Message"],
            "rows": [["No login statistics available."]],
        }

    # --------------------
    # Audit Summary
    # --------------------
    audit_summary = data.get("auditSummary")
    if audit_summary:
        rows = [["Total Events", audit_summary.get("total", 0)]]

        for event, count in audit_summary.get("events", {}).items():
            rows.append([event, count])
    else:
        rows = [["No audit events found for this user.", ""]]

    spec["Audit Summary"] = {
        "headers": ["Metric", "Count"],
        "rows": rows,
    }

    # --------------------
    # Role Summary
    # --------------------
    role_summary = data.get("roleSummary")
    if role_summary:
        rows = [
            [
                r.get("role_name"),
                r.get("scope"),
                r.get("assigned_date"),
            ]
            for r in role_summary
        ]
        headers = ["Role", "Scope", "Assigned Date"]
    else:
        headers = ["Message"]
        rows = [["No roles assigned to this user."]]

    spec["Role Summary"] = {
        "headers": headers,
        "rows": rows,
    }

    # --------------------
    # Password Events
    # --------------------
    password_events = data.get("passwordevents")
    if password_events:
        rows = [
            ["Total password reset events", password_events.get("total_password_reset_events", 0)],
            ["Active reset tokens", password_events.get("active_reset_tokens", 0)],
        ]
    else:
        rows = [["Message", "No password-related events recorded."]]

    spec["Password Events"] = {
        "headers": ["Metric", "Value"],
        "rows": rows,
    }

    return spec

def user_audit_history_to_workbook_spec(payload: dict) -> dict:
    """
    Convert user audit history payload into workbook spec.

    Expected payload structure:

    {
        meta: {...},
        data: {
            report_info: {...},
            audit_stats: {...},
            history: [...]
        }
    }
    """

    if not payload:
        raise ValueError("Empty user audit history payload")

    spec = {}

    data = payload.get("data", {})

    report_info = data.get("report_info", {})
    audit_stats = data.get("audit_stats", {})
    history = data.get("history_rows", [])

    # -------------------------------------------------
    # Sheet 1: Report Info
    # -------------------------------------------------

    if report_info:
        rows = [
            ["Generated By", report_info.get("generated_by")],
            ["Generated At", report_info.get("generated_at")],
            ["User Public ID", report_info.get("user_public_id")],
            ["User Email", report_info.get("user_email")],
            ["User Full Name", report_info.get("user_full_name")],
            ["Start Date", report_info.get("start_date")],
            ["End Date", report_info.get("end_date")],
            ["Total Events", report_info.get("total_events")],
        ]
    else:
        rows = [["Message", "No report metadata available."]]

    spec["Report Info"] = {
        "headers": ["Field", "Value"],
        "rows": rows,
    }

    # -------------------------------------------------
    # Sheet 2: Audit Stats
    # -------------------------------------------------

    if audit_stats:
        rows = [[event_type, count] for event_type, count in audit_stats.items()]
    else:
        rows = [["No audit events recorded for this user.", ""]]

    spec["Audit Stats"] = {
        "headers": ["Event Type", "Count"],
        "rows": rows,
    }

    # -------------------------------------------------
    # Sheet 3: History
    # -------------------------------------------------

    if history:
        rows = history
    else:
        rows = [["No audit history found for this user.", ""]]

    spec["History"] = {
        "headers": [
            "Timestamp",
            "Event Type",
            "Description",
            "Target Model",
            "Target ID",
            "Target Name",
            "Department",
            "Location",
            "Room",
            "IP Address",
            "User Agent",
        ],
        "rows": rows,
    }

    return spec


def user_login_history_to_workbook_spec(payload: dict) -> dict:

    if not payload:
        raise ValueError("Empty login history payload")

    spec = {}

    report = payload.get("data", {})

    target = report.get("target_user", {})
    start_date = report.get("start_date")
    end_date = report.get("end_date")
    generated_by = report.get("generated_by")

    data = report.get("data", {})
    # ---------------------------------
    # Summary Sheet (ONLY sheet with metadata)
    # ---------------------------------

    summary = data.get("summary_stats", {})

    rows = [
        ["Generated At", timezone.now()],
        ["Generated By", generated_by],
        ["Target User Public ID", target.get("public_id")],
        ["Target User Email", target.get("email")],
        ["Start Date", start_date],
        ["End Date", end_date],
        [],
        ["Metric", "Value"],
    ]

    for k, v in summary.items():
        rows.append([k.replace("_", " ").title(), v])

    spec["Summary"] = {
        "headers": [],
        "rows": rows,
    }

    # ---------------------------------
    # Session Stats
    # ---------------------------------

    session_stats = data.get("session_stats", {})

    spec["Session Stats"] = {
        "headers": ["Metric", "Value"],
        "rows": [
            [k.replace("_", " ").title(), v]
            for k, v in session_stats.items()
        ],
    }

    # ---------------------------------
    # Login History
    # ---------------------------------

    history = data.get("login_history", [])

    spec["Login History"] = {
        "headers": [
            "Timestamp",
            "Event Type",
            "Description",
            "IP Address",
            "User Agent",
            "Department",
            "Location",
            "Room",
        ],
        "rows": [
            [
                r.get("timestamp"),
                r.get("event_type"),
                r.get("description"),
                r.get("ip_address"),
                r.get("user_agent"),
                r.get("department"),
                r.get("location"),
                r.get("room"),
            ]
            for r in history
        ],
    }

    # ---------------------------------
    # IP Breakdown
    # ---------------------------------

    spec["IP Breakdown"] = {
        "headers": ["IP Address", "Login Count", "First Seen", "Last Seen"],
        "rows": [
            [
                r.get("ip_address"),
                r.get("count"),
                r.get("first_seen"),
                r.get("last_seen"),
            ]
            for r in data.get("ip_breakdown", [])
        ],
    }

    # ---------------------------------
    # Device Breakdown
    # ---------------------------------

    spec["Device Breakdown"] = {
        "headers": ["User Agent", "Login Count"],
        "rows": [
            [r.get("user_agent"), r.get("count")]
            for r in data.get("device_breakdown", [])
        ],
    }

    # ---------------------------------
    # Login Timeline
    # ---------------------------------

    spec["Login Timeline"] = {
        "headers": ["Date", "Login Count"],
        "rows": [
            [r.get("day"), r.get("count")]
            for r in data.get("login_timeline", [])
        ],
    }

    return spec