# Generated by Django 5.2.15 on 2026-06-21 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ROOM_VIEWER', 'Room Viewer'), ('ROOM_CLERK', 'Room Clerk'), ('ROOM_ADMIN', 'Room Admin'), ('LOCATION_VIEWER', 'Location Viewer'), ('LOCATION_ADMIN', 'Location Admin'), ('DEPARTMENT_VIEWER', 'Department Viewer'), ('DEPARTMENT_ADMIN', 'Department Admin'), ('SITE_ADMIN', 'Site Admin')], db_index=True, max_length=40)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access.permission')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
