# Generated by Django 5.2.15 on 2026-06-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
        migrations.AddField(
            model_name='permission',
            name='domain',
            field=models.CharField(db_index=True, default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='scope_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
