# Generated by Django 5.2.15 on 2026-06-24 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_rolepermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['domain', 'code']},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role', 'permission__domain', 'permission__code']},
        ),
    ]
