# Generated by Django 5.2.15 on 2026-06-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_alter_permission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['sort_order', 'domain', 'code']},
        ),
        migrations.AddField(
            model_name='permission',
            name='is_configurable',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
